### ISSUE TITLE
Problem of predefined function of Root

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#101]
I defined an common equation like x^2+x-12=0

We could easily get two roots, among which the smaller one is -3,the bigger one is 4,but Calcpad only gives the first root.

**Comment by Proektsoftbg** [comment]
Yes, because this is the way numerical methods work in general. In fact, you do not need the `$Root `method to solve simple equations. It is always better to solve them analytically and find a formula, than using numerical methods. We have developed such procedures for quadratic and cubic equations:

https://github.com/Proektsoftbg/Calcpad/tree/main/Examples/Mathematics

You can wrap them in macros, and use #inculde to insert them in any worksheet, like `quadratic_equation$(a$; b$; c$)`;

You can easilly make the `$Root` method to find more roots for particular functions by dividing the interval into parts and appying `$Root `separately for each part. This is just a few lines of code to add, when writing your program.
Additionally, you can use `$Inf` and `$Sup` functions to find the peaks automatically and use them to subdivide the interval.

However, it is possible to create a general procedure that finds all the roots of any polynom, but we need to implement the vectors and matrices before that. Otherwise, we cannot return the answer which is a vector.

**Comment by idealkindom** [comment]
> Yes, because this is the way numerical methods work in general. In fact, you do not need the `$Root `method to solve simple equations. It is always better to solve them analytically and find a formula, than using numerical methods. We have developed such procedures for quadratic and cubic equations:
> 
> https://github.com/Proektsoftbg/Calcpad/tree/main/Examples/Mathematics
> 
> You can wrap them in macros, and use #inculde to insert them in any worksheet, like `quadratic_equation$(a$; b$; c$)`;
> 
> You can easilly make the `$Root` method to find more roots for particular functions by dividing the interval into parts and appying `$Root `separately for each part. This is just a few lines of code to add, when writing your program. Additionally, you can use `$Inf` and `$Sup` functions to find the peaks automatically and use them to subdivide the interval.
> 
> However, it is possible to create a general procedure that finds all the roots of any polynom, but we need to implement the vectors and matrices before that. Otherwise, we cannot return the answer which is a vector.

Thanks a lot for your instructions, my problem arises from my adaption to symbolic manipulation done by Maxma. Maybe from this example I can understand the standpoint of Calcpad better.Thanks again.

**Comment by Proektsoftbg** [comment]
Calcpad is not a symbolic computer algebra system (CAS). 

It is a simple and practical tool for programming of engineering calculation notes. So, symbolic calculations are not included, but also not necessary. In case you need symbolic calculations, you can use one of the many available CAS and then, copy the formulas, you obtained, in Calcpad. Nothing can stop you to use both, each for the job that is suitable for. :)
