### ISSUE TITLE
v5.9.0 forced output units is broken

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#108]
```nginx
F = 10kN
A = 100mm^2
σ = F/A|MPa'shows kPa
```

**Comment by Proektsoftbg** [comment]
Hi,

Thank you! I updated the 5.9.0 release:
https://github.com/Proektsoftbg/Calcpad/releases/download/v5.9.0/calcpad-setup-en-x64.exe

You can have a try. I think that this one and other issues were fixed. It is now stable and not lagging so much on large files.
I only need to make it recognize variables and functions, defined in macros. Now, I can also add step-by-step execution with #pause. Then I will make an official release 5.9.1.

**Comment by cser** [comment]
Yes! It show units normally now, I'll try to test it more tomorrow

**Comment by cser** [comment]
I tried to open previous calculations - it freezes and no effect after "Compile to input form" unpressing.
Try to copy text - it removes some spaces and bringing it back isn't trivial. Try to paste it into Calcpad for example:
```
#def STANDARD$(mode$)
	#if standard ≡ 1
		#if mode$ ≡ 1
			'<span/>ГОСТ 8734-75 Холодно деформированные трубы
		#else if mode$ ≡ 2
			'<span/>ГОСТ 8734-75 Холодно деформированные трубы
		#end if
	#end if
#end def
```

**Comment by cser** [comment]
It freezes after unpressing "Compile to input form" even for one code line, even if file vas not saved and just runned

**Comment by Proektsoftbg** [comment]
@cser  Did you install also .NET7.0?

**Comment by cser** [comment]
@Proektsoftbg
It wasn't work without NET7.0

**Comment by cser** [comment]
@Proektsoftbg
I tried second time now. Just write `x=1`, press "Run", press "Compile to input form", press "Compile to input form" again - freezes happened >_<.

**Comment by cser** [comment]
@Proektsoftbg
Okay, I'll go back to the old version if necessary. It doesn't matter now.

Happy New Year, Ned!

**Comment by Proektsoftbg** [comment]
@cser Thank you for reporting this. I found where the problem was and fixed it.
In the last few days, I performed significant refactoring, optimization, bug fixing and testing.

This was needed because of additional parsing load. Before, Calcpad relied heavilly on manipulation on String and StringBuilder objects. It was OK, but now, it slows down the program and causes intensive memory use and preasure on GC. That is why, I switched to memory spans. This improved the performance very much but introduced new bugs that needed to be fixed.

It should work fine now. I updated the 5.9. release. You can uninstall it and make clean install from the link:
https://github.com/Proektsoftbg/Calcpad/releases/download/v5.9.0/calcpad-setup-en-x64.exe

Happy New Year, my friend! I wish you health and good lock! And the same to all other Calcpad friends.

**Comment by hildebrandopsj** [comment]
Happy New year guys!

I wish all the besta for you all!

Best regards

Em sáb, 31 de dez de 2022 13:06, Ned Ganchovski ***@***.***>
escreveu:
