### ISSUE TITLE
possibility to auto-calculation or live document

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#11]
hi,

many similar apps doing auto-calculation and makes the document live, every single change in variable values, units or equation/formula will give instant answer at the display.

another unfamiliarity is in typing of longer calculation pages,  still required 'enter' or 'run' button pressed. the display calculations always bring to the top of pages by default. so the user need to scroll down to the last equation previously typing to review. 

hopefully these feature and behavior as similar apps been interested to implement.

best wishes,

**Comment by Proektsoftbg** [comment]
Nice suggestion, thank you.

Please note that Calcpad works differently than, say MathCAD. It uses programming-like style rather than graphical formula editing. So, each time you run the program, it needs to parse the source code, check for errors, compile, execute, generate the html output and load it into the output window.

However, it is possible to implement such a feature in Calcpad too. We can add something as "**LIVE**" button to switch on. It can be really convenient for most cases. I am only afraid that it may be slow for large and heavy programs, but we can do this asynchronously in the background. We can also synchronize the scrolling of both windows.

I will add this to the wishlist for the next major release.

**Comment by xyont** [comment]
thanks for explanations, may have a key press to 'run' e.g F5 and bring to the last formula typed could make the user easiness.

**Comment by cser** [comment]
I'm sure that "Input form" must be removed and integrated into "Display output". It's seems to be hard but it makes automatic recalculation after every change is more simple and usable.

Another problem with "Input form" mode - it always show input fields even control flow doesn't reach it (i.e. this input data don't need to calculation).

**Comment by Proektsoftbg** [comment]
Thank you for your suggestion. However, Input forms are a very important feature. They allow other users to work safe with your programs without having access to your source code. So, you cannot remove them. In this way, we use Calcpad to build a professional library of structural design software, much faster than pure .NET Core or ASP.NET Core MVC: https://calcpad.eu/Worksheet/34/shear-design-of-rectangular-section .Calcpad is made so, that you can develop for web and desktop in exactly the same way.

Having input forms does not stop you from using Calcpad for simple everyday calculations. You can just not use it. Or your can use them in source code mode. You can click on "?" marks and change values.

The main problem is to synchronize the input and output. This is because Calcpad is build to work as a programming language, as I mentioned above. So, there is no one-to-one correspondence between the lines in the code and in the output. On the other hand, that makes Calcpad much more flexible that Excel, MathCAD or SMath. You can split the calculations by programming, but also show different content in the report depending on some intermediate checks. It is very common for the structural design.

And yes, it is possible to control what input fields to show. We do this with a little Html and JS/JQuery even before calcs are performed. If you need it, I can send you such a template. You can check this example: https://calcpad.eu/Worksheet/71/sls-design-of-beam-with-rectangular-section .When you select an option, the image changes.

Having the option to insert Html, CSS, JS and SVG in the text provides huge opportunities to create rich UI for your worksheets. However, basic input fields are fine for most cases and very easy to add.

**Comment by Proektsoftbg** [comment]
And there is a good news! :) I found a way to provide correspondence between input and output. I did this by adding id's to Html elements in the output, pointing to the respective line numbers in the source code.
So, it was not very easy, but I managed to do both things you requested:
 - **F5** shortcut to start calculations manually and
 - automatic synchronization of the results in "**AutoRun**" mode.

They are updated each time you finish typing and leave the current line. It actually works quite smoothly. The view is also scrolled to match the source code. For more details, you can check the latest release:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.6.3

Enjoy!
![image](https://user-images.githubusercontent.com/90918363/156893462-7e0c8854-b1ca-4c71-a367-df5214ca1ec5.png)

BTW, you can find the example from the screenshot along many others in the repository:

https://github.com/Proektsoftbg/Calcpad/tree/main/Examples

You can use them to build your own worksheets further.

**Comment by cser** [comment]
> F5 shortcut to start calculations manually and

Thank you very much!

> automatic synchronization of the results in "AutoRun" mode.
> The view is also scrolled to match the source code. For more details, you can check the latest release:

- Two-panel markdown editor experience shows that it's impossible to make fine code and view synchronization :(
- The scrolling to beginning of the document after recalculation was annoying in previous versions of CalcPad.
- The loss of the scroll still annoying after this changes, even when it scrolls to caret position (it's clear that not always, sometimes scrolling to caret is very useful)

So:
- May be just recover scroll position that user set after recalculation and make separate button "scroll view to caret position" (with shortcut)?
- Or may be make combo box "don't change scroll"/"scroll view to caret"/"scroll to end"?

**Comment by cser** [comment]
> So, you cannot remove them. In this way, we use Calcpad to build a professional library of structural design software, much faster than pure .NET Core or ASP.NET Core MVC

No, I suggest to integrate them in one mode (remove mode, don't remove functional).
It's clear that it's hard - so **it's just my opinion**. I just write only one useful methodic with CalcPad for my job and refused from "?" 
because it requires:
- switching input/display modes;
- using superluous words #pre, #post in code;
- entering variables that don't needed for other input variables in input mode.

It's more simple to write "it's input data". Bun even you make external program product - user will still suffer with switching modes (he wants to see the result immediately when entering).

**Comment by Proektsoftbg** [comment]
Thank you! I think I see your point now. :)

> * May be just recover scroll position that user set after recalculation and make separate button "scroll view to caret position" (with shortcut)?
> 
> * Or may be make combo box "don't change scroll"/"scroll view to caret"/"scroll to end"?

Absolutely! That is exactly how this feature should work! I also realized that it was not quite OK like that. So, it will scroll to cursor only if you double click or Ctrl + Right Arrow. And after recalculation, it will just recover the current scroll. I will update it later today. Thank you very much for your valuable suggestion!

I am also glad that you find Calcpad useful for your work.

**Comment by Proektsoftbg** [comment]
It is not that simple. When you are on the last line and open a new line:
If it just restore the scroll, the new line will remain out of view and you will always have to scroll down.
For that case, we will need to synchronize the view as before.

**Comment by Proektsoftbg** [comment]
Hi,

I updated the software as we discussed. You can download and reinstall from the same link.
I also fixed some little bugs I found, removed some obsolete code and made some little improvements
Since I did not upgrade the version, please uninstall the old one to make a clean install.

Now it restores the scroll after autorun, except when you at the last line. Then it scrolls down to keep it synchronized.
Ctrl + Right Arrow updates the output and scrolls to caret.

**Comment by cser** [comment]
Tested. And... it works as wanted now! (at least with lite testing).
Scrolling to caret by double click/Ctrl+Right is nice to. Thank you, Ned.

**Comment by cser** [comment]
However, when autoupdate is disabled - scrolling still lost. It's not always moves to beginning of document, but it always has another position then before.

**Comment by Proektsoftbg** [comment]
Hi, 
Thank you, I am glad it works!

Without autorun mode, it is not easy to preserve the scroll, because it loads the Quick Help and the previous state is lost. So when you press F5, it scrolls to the caret. The other option is to simply not scroll and start from the beginning. That is what I can do for now. We can work a while like this and maybe improve it in future versions. Now I need to focus on our main products. I will leave this issue open and if you have any ideas, you are welcome to share them here. :)

When you click the calc button - it starts from the beginning as before. I deliberately kept the old mode unchanged. There are a lot of users that are using it for years and we cannot force them to change their habits.

I think that the new mode is good for people that use Calcpad just as every day calculator. For people that are using Calcpad as a programming language, the old mode is more useful. When you have complex programs with UI, and a lot of #if, #repeat, #post, #pre, #hide, real time synchronization becomes tedious. I tried with some heavier programs. Some may take a few seconds to compile and run.

**Comment by cser** [comment]
> Without autorun mode, it is not easy to preserve the scroll, because it loads the Quick Help and the previous state is lost. So when you press F5, it scrolls to the caret. The other option is to simply not scroll and start from the beginning. That is what I can do for now. We can work a while like this and maybe improve it in future versions. Now I need to focus on our main products. I will leave this issue open and if you have any ideas, you are welcome to share them here. :)

Simple idea with 2 points:
- Save scroll position only when user scroll it by mouse, and only when user scroll it. Program never change it without user hands. Even if scroll is overflow - program just scroll to end and doesn't correct value.
- When recalculation ends - program scroll view to current saved value. Even if scrolling to this value happened several times during calculation - nothing problem, even user scroll it during calculation - nothing problem again.

May be ignore this saved value when Help opened. May be not - it will not breaks results view scrolling. May be make second separate value when user scrolls help.

> When you click the calc button - it starts from the beginning as before. I deliberately kept the old mode unchanged. There are a lot of users that are using it for years and we cannot force them to change their habits.

May be you're right

> I think that the new mode is good for people that use Calcpad just as every day calculator. For people that are using Calcpad as a programming language, the old mode is more useful. When you have complex programs with UI, and a lot of #if, #repeat, #post, #pre, #hide, real time synchronization becomes tedious. I tried with some heavier programs. Some may take a few seconds to compile and run.

1. Yes, it's realy good. But it often fails with this mode now - I will write bugreport later.
2. It's more clear now that missing power input mode is not the main problem. Тhe main causes of calculatoin text overcomplication is (not only for the calculation, but elso for the beautiful report):
    - the absence of strings;
    - the absence of multi-line functions;
    - the absence of lists/arrays/matrices.
Сonsidering what you said - you're right - it's no reasons to touch input mode now.

**Comment by Proektsoftbg** [comment]
Yes, the things you listed are of highest priority. We also need vectors and matrices already, so this will be the next feature I am going to add. And I would highly appreciate if you send me your bug report when ready. Thank you for your kind support!

**Comment by Proektsoftbg** [comment]
Yes!!! I found it! :)

It was just the template.html. Now I updated the template and it works. I also fixed the scroll for recalculation with F5.
You can install the updated version now and continue your work. Please, uninstall the old version before that.

**Comment by cser** [comment]
Yes, it doesn't fail now!
...and seems that scroll on F5 works correctly. I will test it more deep later.

**Comment by xyont** [comment]
so many thanks for interested and implementation.

**Comment by cser** [comment]
Nothing has fallen so far.

But. Using Ctrl+Right for shortcut was a mistake O_o.
It's uses in text editor to jump by word. Ctrl+Shift+Right uses for word selection.
So... remains Alt+Right?

**Comment by Proektsoftbg** [comment]
OK. I agree. Thank you! Alt+Right sounds good. :) 

It is good to keep the right arrow involved. It feels like I am sending the content from the left to the right window and this is somehow natural.

**Comment by Proektsoftbg** [comment]
Hi,

I tried, but unfortunately, we cannot use "**Alt**". In all apps, by default, it activates the main menu. After that, it does not want to accept the arrow. I suggest to use "**Ctrl + R**" instead. By default, it aligns the text to the right, which looks funny in Calcpad ("**Ctrl + L**" aligns left). On the other hand "**R**" reminds me for "right", "refresh", "recalculate", etc.

**Comment by cser** [comment]
Hello,
I vote for "Ctrl+Enter" (Ctrl+L, Ctrl+E, Ctrl+R seems to be useless now, but may be they will be useful later).

**Comment by Proektsoftbg** [comment]
OK, Let be "Ctrl+Enter" :) I will change it accordingly.

**Comment by Proektsoftbg** [comment]
I updated the release with "Ctrl+Enter" shortcut instead of "Ctrl+Arrow". Now you can re-install it. :)

**Comment by cser** [comment]
Hi,
I run it - seems to works correctly. So - this feature can be marked as done!

P.S. I tried to install without uninstallation at first - nothing changed, as you warned O_o

**Comment by Proektsoftbg** [comment]
Yes. This is because, I just amended the version and did not updated the version number.
