### ISSUE TITLE
Wrong unit conversion

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#111]
@Proektsoftbg i found some strange conversion when using units like cm^2/m. Look at this code:
```
N_s = 430kN/m
A_s = 13cm^2/m
E_s = 210GPa
ε = N_s/(A_s*E_s)
```
The final results calcpad show is: 1,58*10^-5
But the correct answer is: 1,58*10^-3

**Comment by Proektsoftbg** [comment]
Uh! You are right. This is terrible. Actually, the problem is in cm^2/m which converts improperly. If you only try this:
```
A_s = 13cm^2/m
A_s ' = 13cm
```
I will fix it right away.

**Comment by Proektsoftbg** [comment]
OK, I found where the problem was and fixed it. :)

I updated the 5.9.1, so please download and install it again from the link:
https://github.com/Proektsoftbg/Calcpad/releases/download/v5.9.1/calcpad-setup-en-x64.exe

Please, uninstal the previous version before that.

![image](https://user-images.githubusercontent.com/90918363/211648769-f3483e0b-1620-40fa-a8ed-cca2cd6373a7.png)

**Comment by hildebrandopsj** [comment]
Great! Thanks!
