### ISSUE TITLE
Calling previous variable

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#142]
Hello, a very minor issue.
The autocomplete prompt shows the previously defined variables but does not show it if it was defined in the previous line.
(In the exemple below, it does not show the variable "A_2".
![image](https://user-images.githubusercontent.com/111089248/228589258-e74217fa-cdbf-4ce3-b0b5-36858de71554.png)

**Comment by Proektsoftbg** [comment]
Hi, Thank you for reporting this. It really did as you said. I tried it. It was just because it collected the variables before updating the current line number. Now I fixed it and amended the last v5.9.9 release. You can download the updated files from the same link:

https://github.com/Proektsoftbg/Calcpad/releases/download/v5.9.9/calcpad-setup-en-x64.exe
