### ISSUE TITLE
Custom units in input form

### ISSUE THREAD

**Issue by emanuelemaz** [Proektsoftbg/Calcpad#156]
When custom units are inserted after an input form an error is thrown.
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/4d9f5c11-aed2-45f4-a385-d025397125ee)
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/4f39b882-b7f2-4094-9d69-a4bb0e3acdb8)
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/7a5d26b5-bf96-46be-aad2-93ca91019af7)

**Comment by Proektsoftbg** [comment]
OK. Thank you for your feedback. I will look at it.

Can you please try to insert "*" before the custom units:
`x = ? {10}*€`

It should work this way.

**Comment by emanuelemaz** [comment]
It works this way!
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/8c771f0b-794a-441f-a02d-702ee3b3d1c5)

**Comment by emanuelemaz** [comment]
Thank you for the quick answer :). It works in the calculator but it still fails to parse in input form.
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/8c6d6d87-6e1b-48d9-ac94-29b7d390f28c)
![image](https://github.com/Proektsoftbg/Calcpad/assets/34983402/05b4d598-1b27-46e3-a6f6-7524f1602f6b)

**Comment by Proektsoftbg** [comment]
OK. I see.

The problem is that custom units are created dynamically, after the respective line of code is evaluated.
The problem is that the code is not evaluated in input form mode. Only after you run the calculations.
This is a limitation, that we have to live with for now. However, there are two more workarounds that you can try.

1. Enter units in comments in input phase and add them later in execution phase in a hidden html section:

```
"Custom units in forms example
x = ? {10}'€
'<!--
.€ = 1
x = x*€
'-->
x
```

&lt;!-- and --&gt; starts and ends an Html comment. Even if errors are generated inside in the input form, they will not appear on screen, but in calculation phase, this will work normally.

If you do not need to do any conversions or interactions with other units, you can simply leave them in the comments to the end.

2. The second solution is to use interactive execution with #input breaks that will allow Calcpad to run some code in the beginning and create the variables and prompt for input after that. You can try the following code:

```
"Custom units in forms example
#post
.€ = 1
#pre
'Press F5 to start
#show
#input
x = ? {10}*€
```

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/07c60c68-9d28-455a-baad-9c7385f2cd13)

However, if you do not do any
