### ISSUE TITLE
First solution in interval - root finding

### ISSUE THREAD

**Issue by johnnyontheweb** [Proektsoftbg/Calcpad#162]
Hello,
since I found Calcpad I'm using it for my calculations, it's very useful and easy to use.

Sometimes I need to get the solution for complex functions, and I noticed Calcpad (6.0.6) does not give the first. Please find the image below, in which I reproduced the behaviour with a simple cos(x) - I was expecting 1.57, but $Root gives 7.85.

![calcpad_root_support](https://github.com/Proektsoftbg/Calcpad/assets/10365055/91c776cd-b5cc-4a2b-b909-c3cce97541b4)

How can I force Calcpad to give always the firts solution encountered in the interval, without changing its limits? thanks in advance

**Comment by Proektsoftbg** [comment]
Hi,

This is a common problem of most root finding methods. They are designed to find one root in a given interval. If there are 4several roots, they will find just one. It is not necessary to be the first or any other specific one. It depends on the method and the initial conditions.

If you have such an oscillating function, you can combine the `$Root` function with the `$Inf` and `$Sup` for finding minimum and maximum of a function in your own loop, as follows:

1. Find a root `x_0` in the interval `[a; b]`.
2. If the function in the beginning is `f(a) > 0`, find the minimum with `$Inf` within the interval `[a; x_0]`. If` x_inf = x_0` (no local minimum), this is the first root. Exit the loop.
3. If `x_inf < x_0`, assign `b = x_inf` and loop back to 1.

If `f(a) < 0` do the same but use `$Sup` to find the maximum instead. If there are several roots, this process will converge to the first root, as needed. You can warp this procedure in a macro.

**Comment by johnnyontheweb** [comment]
Mmm, I tried, but no results. Did you mean:
```
f(x) = cos(x)
' macro
#def find_1st_root$(a$; b$)
'loop
#repeat 100'number of repetitions
at = a$
bt = b$
x_0 = $Root{f(x) @ x = at : bt}
#if f(a$) > 0
x_inf = $Inf{f(x) @ x = at : x_0}
#if x_inf ≡ x_0
#break
#else
bt = x_inf
#end if
#else
x_sup = $Sup{f(x) @ x = at : x_0}
#if x_sup ≡ x_0
#break
#else
at = x_sup
#end if
#end if
#loop
#end def

find_1st_root$(0; 10)
$Plot{f(x) @ x = 0 : 10}
```

A couple of general questions:
1. can I pass the function to macro? I mean, using f(x) as param? if I try, it gives me the error "unexpected ("
2. if the answer to previous point is "no", may I have to always call the function "f(x)" to re-use the macro or change the macro accordingly?

A general remark: I understood the point about the root finding methods, anyway a user does not expect to handle something like this (in my case, after hours of struggling I plotted the function I was working with and found out this problem).
Hence, considering performance on one hand and usability on the other, I would decisely prefer the first root is returned automatically.

**Comment by Proektsoftbg** [comment]
Hi, you are almost there, but there are some bugs that prevent the macro from working correctly. However, what you did so far is quite helpful and with minor changes, I could make it work. Here is the correct code, you can use directly:

```
g(x) = (3 - x/3)*cos(x) + sin(x^2/8) - x/16
' Macro
#def find_1st_root$(f$; a$; b$)
	'Loop
	at = a$
	bt = b$0
	ε = 10^-12
	#repeat 10'Max number of repetitions
		x_0 = $Root{f$(x) @ x = at : bt}
		#if f$(a$) > 0
			y_inf = $Inf{f$(x) @ x = at : x_0}
			x_inf
			#if abs(x_inf - x_0) < ε ∨ y_inf ≥ ε
				#break
			#else
				bt = x_inf
			#end if
		#else
			y_sup = $Sup{f$(x) @ x = at : x_0}
			#if abs(x_sup - x_0) < ε ∨ y_sup ≤ 0
				#break
			#else
				bt = x_sup
			#end if
		#end if
	#loop
#end def
x_0 = 0
find_1st_root$(g; 0; 20)
$Root{g(x) @ x = 0 : 20}
$Plot{g(x) & x_0|g(x_0) @ x = 0 : 20}
```
Where the problems were:
1. Do not initialize `at` and `bt` inside the loop. You have to do that **before the loop**. Otherwise, on each iteration you restart everything to its initial state and it will never converge.
2. The $Inf and $Sup functions do not return the x value of the exterma, but the y value (the extremum itself). x_inf and x_sup are assigned automatically in the background.
3. When you compare approximate values from numerical methods, do not compare with "≡", but compare the absolute difference to some small tolerance: `abs(x_1 - x_0) < ε`

I am sorry, but you sound to me a little bit imperative. No one owes nothing to no one here. It is a free and open source software and everything is done entirely by a good will. I spent some valuable time today to help your problem and only expect some little gratitude and I am not taking orders.

1. Calcpad is a programming language that is extensible by macros. And there is a huge variety of problems that can be solved. So, **it is expected** by users to program their own solutions, if possible. And if you can't, it is normal to ask the community for help. Sometimes, it could be useful to learn some more advanced programming. ;)

2. Finding a single root of an equation iteratively and finding the first, last or multiple roots are different problems. As you can see, finding the first root requires a lot of additional computations, and it is a very rare case. So, we cannot just modify the existing method to always find the first root, and make it several times slower just for that. Tomorrow, one may want to get the last root. What shall we do then? I do not know a software that includes a "find the first root" function.

3. After the vectors and matrices are ready, it is planned to add a routine for finding all the roots inside an interval and store them in a vector. Then, you can pick any value you need - first, last or whatever. But it will take time to develop and test.

With this short macro, you have your problem solved today.

**Comment by johnnyontheweb** [comment]
I'm sorry you felt my word as imperative, that wasn't my intention. I only said that, in my expectations, the first solution should be given, as others do (e.g. MathCad). Inevitably, even when using a new software, you expect the same results from the same input.
I'm grateful for the corrected script, I hope this will help also others. Now I know more in deep how Calcpad works.

**Comment by johnnyontheweb** [comment]
Some additional questions:
1. Why b$0 ? I would expect b$ on 6th line
2. I had to define x_inf and x_sup in the script, it is expected or your copy is running without their definition?
3. with a simpler function (I reverted to cos(x) to test), I get `Error in "x_0 = $Root{g(x) @ x = at : bt}" on line [[11](about:blank#0)]: No solution for: $Root{g(x) = 0; x ∈ [at; bt]}.`  Such errors are rendered in output, is there a way to hide them of exit from loop on error?

thanks in advance 

```
x_inf = 0
x_sup = 200
g(x) = cos(x)
'(3 - x/3)*cos(x) + sin(x^2/8) - x/16
' Macro
#def find_1st_root$(f$; a$; b$)
'Loop
at = a$
bt = b$
ε = 10^-12
#repeat 10'Max number of repetitions
x_0 = $Root{f$(x) @ x = at : bt}
#if f$(a$) > 0
y_inf = $Inf{f$(x) @ x = at : x_0}
x_inf
#if abs(x_inf - x_0) < ε ∨ y_inf ≥ ε
#break
#else
bt = x_inf
#end if
#else
y_sup = $Sup{f$(x) @ x = at : x_0}
#if abs(x_sup - x_0) < ε ∨ y_sup ≤ 0
#break
#else
bt = x_sup
#end if
#end if
#loop
#end def
x_0 = 0' init
find_1st_root$(g; x_inf; x_sup)
x_0
$Root{g(x) @ x = 0 : 20}
$Plot{g(x) & x_0|g(x_0) @ x = 0 : 20}
```

**Comment by Proektsoftbg** [comment]
This is because you plugged in `x_inf` and `x_sup` as macro arguments: `find_1st_root$(g; x_inf; x_sup)`. They are special variables. Use them only to retrieve the points of extrema.
Use other variables, say `a` and `b` for interval endpoints if you need some:
```
a = 0
b = 20
find_1st_root$(g; a; b)
x_0
$Root{g(x) @ x = a : b}
$Plot{g(x) & x_0|g(x_0) @ x = a : b}
```

b$0 is a typo. It should be b$.

BTW, MathCAD is also not specially designed to "find the first root" in an interval. It simply uses a different method - the "secant" one, which requires an initial guess point. In recent versions, they introduced a bracketed version, which probably use some hybrid method. It simply happens "by chance" that it find the "first" root (this may happen if the guess point is the left end). If you apply a different method, or select a different guess point, it will find another root.

Calcpad uses the modified Anderson-Bjorks, which is faster and more stable. In all cases, when using numerical methods for root finding, it is good to plot your function first. Based on this, select a good initial point or interval to get the best results. It is also good to know about the methods you are using and how they work. You can start reading here:
https://en.wikipedia.org/wiki/Root-finding_algorithms

About the method in Calcpad, you can read this article:
https://iopscience.iop.org/article/10.1088/1757-899X/1276/1/012010/pdf

Currently, it "beats" all other available methods in term of stability and speed, which can be seed from the test results. :)

**Comment by johnnyontheweb** [comment]
Thanks, I never figured out that the root found all these programs was practically random on the interval. Thanks for the interesting paper!
