### ISSUE TITLE
Cpd Missing

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#192]
Hi @Proektsoftbg !

I notice the examples of strutural design > Steel are gone. 

I trying to see the I Section to implement our national database using the selection data target like the image in the issue https://github.com/Proektsoftbg/Calcpad/issues/26.

Thanks in advance

**Comment by Proektsoftbg** [comment]
Hi!

Sorry, it got "lost" because it was not part of the package, but I added it later for the above discussion. But only on GitHub, not on my local repo. Fortunately, GitHub keeps everything in the history, so it is still there in the respective commit b1008c2 from Apr 30, 2022:

https://github.com/Proektsoftbg/Calcpad/blob/b1008c2bce22e70c341449212590761026f11f3a/Examples/Structural%20Design/Steel/I%20section.cpd

I have more of it with stress checks added, but it is not translated yet - only in Bulgarian. I can send it to you as well if you like, and you can try to translate it with Google Translator. The result is usually not very good, but just enough to see what it is about.

**Comment by hildebrandopsj** [comment]
Thanks @Proektsoftbg! The design spreadsheet it's not needed, thanks! About the translations, the Brazilian portuguese is around 40% now.
