### ISSUE TITLE
2 problems reported

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#196]
Recently I  found 2 problems:
1、Extra Sapce typing between #else and " if " can cause error;
2、calculation contain antitrigonometric functions could easily go wrong if you don't notice that the value of an antitrigonometric might be very big. Still I think it's not advisible to use #rad and #deg to controll the vaule, instead they should only be used to control display. My suggestion is, deg should be used as a unit, while the default is 1,i.e. radian.

**Comment by Proektsoftbg** [comment]
Hi @idealkindom!

Thank you for your feedback! I will take a closer look. About `#end if`, this is the way it is defined in the Calcpad language. These are not two separate literals. The whole `#end if` with just one space is a keyword. And as for any other keywords, if you do not write it exactly as specified, it is not recognized by the parser.

**Comment by idealkindom** [comment]
> 

Yes I guess so,it's the same for space between both #else and if, #end and if.

Pls consider the antitrigonometric calculation problem.Thks a lot.

**Comment by Proektsoftbg** [comment]
Hi, about inverse trigonometric functions, can you please provide more specific details of example:

What is your input, what do you get, and what is expected? Do you get different results if you try the same functions anywhere else, say in Excel or Mathcad?

Is it possible to be simply the floating point math limitations? Just like other similar software, Calcpad internally warps the native processor math functions. They are very fast, but their range and precision are limited by the parameters of the machine environment. On the other hand, processors internally use some kind of CORDIC or BKM algorithms:

https://en.wikipedia.org/wiki/CORDIC
https://www.computer.org/csdl/proceedings-article/afips/1959/50540257/12OmNqN6QXX
https://en.wikipedia.org/wiki/BKM_algorithm
https://www.researchgate.net/publication/220329442_BKM_A_New_Hardware_Algorithm_for_Complex_Elementary_Functions

The other option is to use arbitrary precision arithmetic, like this one:
https://en.wikipedia.org/wiki/GNU_Multiple_Precision_Arithmetic_Library

However, since it is software-emulated, it is hundreds of times slower than using the processor functions. But for most real-world engineering problems, the float64 range and precision should be more than enough.

**Comment by idealkindom** [comment]
> Hi, about inverse trigonometric functions, can you please provide more specific details of example:
> 
> What is your input, what do you get, and what is expected? Do you get different results if you try the same functions anywhere else, say in Excel or Mathcad?
> 
> Is it possible to be simply the floating point math limitations? Just like other similar software, Calcpad internally warps the native processor math functions. They are very fast, but their range and precision are limited by the parameters of the machine environment. On the other hand, processors internally use some kind of CORDIC or BKM algorithms:
> 
> https://en.wikipedia.org/wiki/CORDIC https://www.computer.org/csdl/proceedings-article/afips/1959/50540257/12OmNqN6QXX https://en.wikipedia.org/wiki/BKM_algorithm https://www.researchgate.net/publication/220329442_BKM_A_New_Hardware_Algorithm_for_Complex_Elementary_Functions
> 
> The other option is to use arbitrary precision arithmetic, like this one: https://en.wikipedia.org/wiki/GNU_Multiple_Precision_Arithmetic_Library
> 
> However, since it is software-emulated, it is hundreds of times slower than using the processor functions. For most real-world engineering problems, the float64 range and precision should be more than enough.

OK.let's see an example. L=R*asin(d/R),when d/R=1/2, you get a result asL=20*R, instead of L=2*R. radian is a self consistant unit while degree not, since one circle is 360 degree. I used Maxima a lot for many years, it use radian as default unit for both trigonometric and anti-trigonometric. That's why I suggest the trigonometric and anti-trigonometric function should be in radian as default, while degree must be used as a unit. How do you think??

**Comment by Proektsoftbg** [comment]
Hi! I cannot get anything like this on my computer. Here is my code:
```
d = 1
R = 2*d
#deg
'Degrees
L = R*asin(d/R)
L/R
asin(1/2)'°

'Convert to radians
L = R*asin(d/R)*deg/rad
'or
L = R*asin(d/R)*π/180

#rad
'Radians
L = R*asin(d/R)
L/R
asin(1/2)
```

What I get is that asin(1/2) = 30° in degrees. How do you get 20?

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/0eb839c7-f675-46e0-86fb-6deb01090729)

It is expected that, if you have set to work in degrees, you will get the result in degrees, so you will have to use the respective formula (L = R*asin(d/R)*π/180) or simply change the target units. I think that the most appropriate default units are different for the different engineering fields. So, it is best for everyone to set them by himself. For me as a structural engineer, it is best to use degrees in 95% of cases.

In the latest version, if you change the default units from the UI and close the program, they will be saved and will be loaded each time you start the program after that. However, my recommendation is not to rely on the default settings, but to specify explicitly the units at the beginning of each worksheet (#deg, #rad, or #gra). In this way, if you open it in the future with different settings, you will not get different results.

**Comment by idealkindom** [comment]
Sorry, that's my typing error. I also got 30.
















At 2023-09-11 19:52:38, "Ned Ganchovski" ***@***.***> wrote:

Hi! I cannot get anything like this on my computer. Here is my code:

d = 1
R = 2*d
#deg
'Degrees
L = R*asin(d/R)
L/R
asin(1/2)'°

'Convert to radians
L = R*asin(d/R)*deg/rad
'or
L = R*asin(d/R)*π/180

#rad
'Radians
L = R*asin(d/R)
L/R
asin(1/2)


What I get is that asin(1/2) = 30° in degrees. How do you get 20?

It is expected that, if you have set to work in degrees, you will get the result in degrees, so you will have to use the respective formula (L = R*asin(d/R)*π/180) or simply change the target units. I think that the most appropriate default units are different for the different engineering fields. So, it is best for everyone to set them by himself. For me as a structural engineer, it is best to use degrees in 95% of cases.

In the latest version, if you change the default units from the UI and close the program, they will be saved and will be loaded each time you start the program after that. However, my recommendation is not to rely on the default settings, but to specify explicitly the units at the beginning of each worksheet (#deg, #rad, or #gra). In this way, if you open it in the future with different settings, you will not get different results.

**Comment by Proektsoftbg** [comment]
OK, I see. So, we can now both agree that the result is correct for the selected units. You can set whatever defaults you prefer, but in all cases, you have to keep in mind what units you are using.

It is also strange to multiply angles by lengths directly. You'd rather obtain the angle from `asin`, but after that use it with `cos` or `tan` to calculate another length, instead of the angle itself, say:
```
α = asin(a/c)
b = c*cos(α)
```
I think there is nothing to be fixed.
