### ISSUE TITLE
Plot not working as expected

### ISSUE THREAD

**Issue by FEA-eng** [Proektsoftbg/Calcpad#198]
Hi,

just a question - what's wrong with my syntax that I don't get a proper plot?

l = 1000mm
g = 9810mm/s^2
θ_start = 45deg
θ_end = 180deg
ω = sqrt(((3*g)/l)*(cos(θ_start) - cos(θ_end)))
v = ω*l
v(θ_end) = ω*l
$Plot{v(θ_end) @ θ_end = 45deg : 180deg}

![plot](https://github.com/Proektsoftbg/Calcpad/assets/59876896/852a811e-9dff-4f6e-9cf4-25aa924a7571)

Is it because of degrees? Btw. there's no option to adjust the range of the y axis, right?

**Comment by Proektsoftbg** [comment]
The problem is that the function is constant. It does not depend on the parameter θ_end:
`v(θ_end) = ω*l`

And the units are somehow strange:  g^0.5/mm^0.5. So, it is difficult for Calcpad to scale it.

You can adjust the y axis scaling by plotting some additional points, like:
`$Plot{v(θ_end) & θ_start|0 @ θ_end = 45deg : 180deg}`

**Comment by FEA-eng** [comment]
Thank you for the quick reply. It's working when I substitute the formula for ω:

`v(θ_end) = (sqrt(((3*g)/l)*(cos(θ_start) - cos(θ_end))))*l`

I just wonder why it cuts the bottom axis at 300 when I use:

l = 1000mm
g = 9810mm/s^2
θ_start = 45deg
θ_end = 360deg
v(θ_end) = (sqrt(((3*g)/l)*(cos(θ_start) - cos(θ_end))))*l
$Plot{v(θ_end) @ θ_end = 45deg : 360deg}

![plot](https://github.com/Proektsoftbg/Calcpad/assets/59876896/dfc9b68c-a1a7-47f9-9cff-c434bdb61e04)

**Comment by Proektsoftbg** [comment]
When a plot is too far from the x-axis, say: y = 9000 to 10000, it automatically cuts the empty bottom part under 9000. Otherwise, you will not see the shape of the function, but some almost straight line up there.

In most cases it works fine. Even for constant functions:
`$Plot{100 @ x = 0 : 100}`
![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/0d5ce630-f426-44fb-a905-926701e6e284)

Probably, the output units of g^0.5/mm^0.5 play some trick here.

**Comment by FEA-eng** [comment]
Thank you for the explanation. I was trying to get a plot like this (here in radians):

![plot](https://github.com/Proektsoftbg/Calcpad/assets/59876896/5d2a0b16-a88b-4e61-8f1c-a8dc8b1163ea)

**Comment by idealkindom** [comment]
> Hi! The problem is that the function is constant. It does not depend on the parameter θ_end: `v(θ_end) = ω*l`
> 
> And the units are somehow strange:  g^0.5/mm^0.5. So, it is difficult for Calcpad to scale it.
> 
> You can adjust the y axis scaling by plotting some additional points, like: `$Plot{v(θ_end) & θ_start|0 @ θ_end = 45deg : 180deg}`

Hoping more features could be introduced for plotting, such as legend, line type, color, and symbols, which are very important for manifest.

**Comment by Proektsoftbg** [comment]
@idealkindom Yes this is definitely needed. I have started a discussion of what is planned so far:
https://github.com/Proektsoftbg/Calcpad/discussions/175

If any suggestions and ideas, please feel free to comment.

**Comment by Proektsoftbg** [comment]
Maybe instead of developing everything from scratch we can integrate some open source JS plot lybrary like this one:
https://github.com/plotly/plotly.js/

Then we can have even more fantastic feature like 3D, animation and hundred of styles and formats?

**Comment by idealkindom** [comment]
All that needed for desent plot are axis label, axis scale(log,ln),legends of lines, line type and color, symbols like asterisks etc., the setting of density of symbols. In addtion, all the labeling texts font should be resizable.
















At 2023-09-22 01:02:14, "Ned Ganchovski" ***@***.***> wrote:

@idealkindom Yes this is definitely needed. I have started a discussion of what is planned so far:
#175

If any suggestions and ideas, please feel free to comment.

**Comment by idealkindom** [comment]
That would be more efficient to introduce  mature features.
















At 2023-09-22 01:07:29, "Ned Ganchovski" ***@***.***> wrote:

Maybe instead of developing everything from scratch we can integrate some open source JS plot lybrary like this one:
https://github.com/plotly/plotly.js/

Then we can have even more fantastic feature like 3D, animation and hundred of styles and formats?

**Comment by Proektsoftbg** [comment]
Hi! I found where the problem was and fixed it in the latest release:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.1.5

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/3c17d07c-97c8-4d49-aca5-f27fa42c46ec)

**Comment by FEA-eng** [comment]
> Hi! I found where the problem was and fixed it in the latest release: 

Hi, thank you for fixing this but I think that I've found a similar issue here:

L = 1100mm
w = 400mm
t = 10mm
F = 10000N
E = 9GPa
I = (w*(t^3))/12
W_z = (w*(t^2))/6
M_max = (F*L)/4
σ = M_max/W_z
y_max(t) = (F*(L^3))/(48*E*I)
$Plot{y_max(t) @ t = 10mm : 100mm}

It works properly only when I replace `I` in `y_max(t)` with `((w*(t^3))/12)`,

But then the y axis is in meters. Can I change it to mm somehow ?

![plot](https://github.com/Proektsoftbg/Calcpad/assets/59876896/e4bc1bd4-21c7-4937-8053-833363beed8b)

**Comment by Proektsoftbg** [comment]
Hi!

This is not related to plotting.
First, you have to define `I` to be also a function of `t`:
`I(t) = (w*(t^3))/12`

Then if you want `y_max(t)` to plot in mm, you have to force it to evaluate to mm. In Calcpad, this is performed by adding `|mm` fust after the equation:
`y_max(t) = (F*(L^3))/(48*E*I(t))|mm`

And that is all, everything works as expected:

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/011ca359-5d90-4e74-af68-0a34342b5723)

**Comment by FEA-eng** [comment]
Perfect, thank you for the explanation :-)

**Comment by idealkindom** [comment]
hey,the problem is that you did not define y_max(t) properly.
















At 2023-10-03 18:20:07, "FEA-eng" ***@***.***> wrote:

Hi! I found where the problem was and fixed it in the latest release:

Hi, thank you for fixing this but I think that I've found a similar issue here:

L = 1100mm
w = 400mm
t = 10mm
F = 10000N
E = 9GPa
I = (w*(t^3))/12
W_z = (w*(t^2))/6
M_max = (FL)/4
σ = M_max/W_z
y_max(t) = (F(L^3))/(48EI)
$Plot{y_max(t) @ t = 10mm : 100mm}

It works properly only when I replace I in y_max(t) with ((w*(t^3))/12),

But then the y axis is in meters. Can I change it to mm somehow ?
