### ISSUE TITLE
° as unit like in Mathcad

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#20]
So, using unit `°` in Mathcad is more simple clear that `#rad/#deg` switching.
I suggest to introduce `°` unit (the lone symbol is not occupied, am I right?) without `#rad/#deg` behaviour chaning:
```
α=90°
α
α|°
```
Shows:
```
α=90°
α=1.5708
α=90°
```
The main point is that `unitless` and `°` must be compatible.
When `#rad` using the value of `sin(90°)` is 1 - it's clear.
What happened when `#deg` enabled and `sin(90°)` using? - It's a problem, but let it shows 0.2741 - backward compatibility is more expensive. Another problem is default mode `#deg` - may be it's need to show **"⚠RECOMMENDED TO USE #rad MODE WITH °"**  if `°` exists in code and `#rad` missing.

**Comment by Proektsoftbg** [comment]
OK. That is easy to do. I will include it in the next version.

**Comment by Proektsoftbg** [comment]
Degrees units for angles were added. 
![image](https://user-images.githubusercontent.com/90918363/174311598-f7673817-8309-4c60-8743-ccd0d470ad6e.png)

I amended the 5.7 release, so you can download it again and try it.
Although angles are dimensionless, the "°" cannot be directly added with unitless numbers. It looks ugly. You need to convert them also in degrees. It will be the same when we add other dimensionless units in future like informational (bit, byte...) or currency.

**Comment by cser** [comment]
Thank you!
It's made more convenient than I expected O_o.
![image](https://user-images.githubusercontent.com/655339/174489881-e9fceb74-0a83-43b2-8aef-e6c8423a7834.png)

**Comment by cser** [comment]
I was in a hurry. Sorry. Current realization of ° is too unobvious:
```nginx
#deg
"#deg ----------------------------

f = 1/10' = 0.1
f|°' = 5.73°
f' = 0.1
sin(f/1°)' = 0.00175

f = 1/10|°' = 5.73°
f|' = 5.73° - how to show rads?
sin(f/1°)' = 0.0998 - f is still 0.1 rad, but result is anoher !!!

π/180°' = 0.175, but my mind expected 1 !!!

#rad
"#rad ----------------------------

f = 1/10' = 0.1
f|°' = 5.73°
f' = 0.1
sin(f/1°)' = 0.00175

f = 1/10|°' = 5.73°
f|' = 5.73° - how to show rads?
sin(f/1°)' = -0.526 - f is still 0.1 rad, but result is anoher !!!

π/180°' = 0.175, but my mind expected 1 !!!
```
IMHO:
- need to do it as in Mathcad - fully compatible ° and unitless (i.e. 1°≡π/180);
- need "unitless" unit to force rads showing and name it as 'rad' or just '|' without unit.
- it makes dangerous cos, sin, e.t.c functions using with `deg` mode and `°`, but now we have a bigger problem.
I.e. expected this behaviour:

```nginx
#deg
"#deg ----------------------------

f = 1/10' = 0.1
f|°' = 5.73°
f|' = 0.1
sin(f/1°)' = 0.00175

f = 1/10|°' = 5.73°
f|' = 0.1
sin(f/1°)' = 0.309, sin(18) in #deg mode

π/180°' = 1

#rad
"#rad ----------------------------

f = 1/10' = 0.1
f|°' = 5.73°
f' = 0.1
sin(f/1°)' = 0.00175

f = 1/10|°' = 5.73°
f|' = 0.1
sin(f/1°)' = -0.75, sin(18) in #rad mode

π/180°' = 1
```

**Comment by Proektsoftbg** [comment]
Angles are dimensionless (in terms of physics) but they are still units and follow the same logic as other units which is a better approach. This will apply also when we introduce money as units (to make cost calculations) or information units (bit, byte, etc.)

#deg and #rad modes does not affect how '°' units or 3.14 (without units) are treated. They only affect how (unitless) arguments of trigonometric functions are treated. In #deg mode it doesn't make difference if you use '°' units or not because everything is treated as degrees anyway. It makes difference only in #rad mode. It is an alternative and newer approach to #deg. Just use one of both. 

These are two different concepts. But I cannot just erase #deg and #rad options just like that. It will make thousands of existing worksheets to stop working. After some time when the alternative approach become mature enough we will make the old one obsolete and will remove it. But we have to announce this in advance and give time to users to rewrite their worksheets.

So, in #deg mode, `sin(f/1 °) = sin(5.73 °/1 °) = sin(5.73) = 0.0998 ` It is exactly the same as you just write `sin(5.73)`. You will get the same result `= 0.0998`. This is the purpose of #deg mode - to treat argments as degrees. The introduction of '°' units have not changed this behaviour.

In rad mode it is `sin(f/1°)' = sin(5.73°/1°) = sin(5.73) = -0.525`. This is correct - sin(5.73) = -0.525 if 5.73 is in radians.

The confusion comes from the fact that you expect that 3.14 is the same as 3.14rad. But this will happen if we introduce rad units. Then `180°/3.14rad =  3.14rad/180° = 1`. Until then, 180°/3.14 = 57.3 ° and 3.14/180° = 1/57.3 ° = 0.0175 (1/°). The problem I see is that the program misses the 1/° units in the output, but it is there. I will fix that,
So, think about π/180° as a conversion factor from deg to rad. Try the following:
```
k = π/180° '= 0.0175 
α_deg = 90° ' = 90 °
α_rad = α_deg*k ' = 90 °·0.0175  = 1.57
```
What I like now is that when I write `90°/2` I get `45°`. In MathCAD< when I write the same, I always get `= 0.7854`. This is not good. So '°' are not true units but just a hidden factor of 0.0175, which is immediately applied. I want to do it better - to keep the units in all arithmetic operations and convert them only inside trigonometric functions., So, I think that what you only miss is the other angle units as **rad** and possybly, **grad**. I can add this easilly but I need to finish the macro implementation first, before publishing the new version. Otherwise we will create a mess.

**Comment by cser** [comment]
> The problem I see is that the program misses the 1/° units in the output, but it is there

Seems to be true: `π/180° = 0.0175°⁻¹` - is OK, but `π/180° = 0.0175` - is strange`

> These are two different concepts. But I cannot just erase #deg and #rad options just like that. It will make thousands of existing worksheets to stop working. After some time when the alternative approach become mature enough we will make the old one obsolete and will remove it. But we have to announce this in advance and give time to users to rewrite their worksheets.

Even after deprecation it's bad to remove them. Users like to think that their code will still work even after 20 years

**Comment by cser** [comment]
But anyway, this is a trap:
```nginx
a = 10|°
b = 10
sin(a)'=-0.544
sin(b)'=0.174
```
The calculation result should not depend on the way the value is displayed

**Comment by Proektsoftbg** [comment]
But it is not just displayed. The units are stored inside the variable together with the value. And of course they affect the results. It is not the same if you have `a = 10m` or `a = 10mm`. In the same way, it is not the same if you have `a = 10rad` or `a = 10°`.
It is also not the same if you write `a = 10°` or a = 10|°. In the first case you will just have `a = 10°` and `sin(a) = 0.174` as expected. 

In the second case, you have `a = 10rad`, converted to °, which makes `a = 572.96 °`. I believe, you see this in the results. What I get on my side is `sin(a) = sin(572.96 °) = -0.544`. I suggest to wait for rads and grads and if you write your examples with the complete angle unit system, it will be quite clear.
