### ISSUE TITLE
About "open with MS word"

### ISSUE THREAD

**Issue by ThomsonTanminxin** [Proektsoftbg/Calcpad#206]
It seems <td align = "left"> and table{width:100%;} don't work as expected when the output is opened with MS word, however, they work as expected when output is saved as PDF or HTML file. The script is as below, please help to check if any errors in my file. Or, is it the problem of my MS word 365 (version of 2016)?
'<style >
'table,th,td{border:2px solid;} td{vertical-align:middle;} table{width:100%; }
'</style > 
'<h3>1. Line Main Protection Setting List </h3>
'<h4>1.1 System settings</h4>
'<table class="bordered"  text-align = "Left">
  '<thead> 
    '<tr> 
      '<th> No. </th> 
      '<th> Name </th> 
      '<th> Range </th> 
      '<th> Value </th> 
      '<th> Unit </th> 
      '<th> Description </th> 
    '</tr> 
  '</thead> 
  '<tbody> 
    '<tr> 
      '<td align = "center">1</td> 
      '<td align = "left">ActiveGrp</td> 
      '<td align = "left">1~30</td> 
      '<td align = "center">1</td> 
      '<td align = "center">&nbsp</td> 
      '<td align = "left" text-align = "left">Current active setting group</td> 
    '</tr> 
    '<tr> 
      '<td align = "center">1</td> 
      '<td align = "left">Grp</td> 
      '<td align = "left">1</td> 
      '<td align = "center">1</td> 
      '<td align = "center">&nbsp</td> 
      '<td align = "left" text-align = "left">group</td> 
    '</tr> 
'</tbody>
'</table>
'<h4>1.2 Line settings</h4>
'<table class="bordered">
  '<thead> 
    '<tr> 
      '<th> No. </th> 
      '<th> Name </th> 
      '<th> Range </th> 
      '<th> Value </th> 
      '<th> Unit </th> 
      '<th> Description </th> 
    '</tr> 
  '</thead> 
  '<tbody> 
    '<tr> 
      '<td align = "center">1</td> 
      '<td align = "">Z1L</td> 
      '<td align = "left">(0.05~655)/In</td> 
      '<td align = "center">Z_L1_sec</td> 
      '<td align = "center">ohm</td> 
      '<td align = "left">Positive-sequence impedance of the whole line (secondary value)</td> 
    '</tr> 

  '<tbody> 
    '<tr> 
      '<td align = "center">1</td> 
      '<td align = "">Z0L</td> 
      '<td align = "left">(0.05~655)/In</td> 
      '<td align = "center">1</td> 
      '<td align = "center">ohm</td> 
      '<td align = "left">zero</td> 
    '</tr> 
'</tbody>
'</table>

**Comment by Proektsoftbg** [comment]
Hi, 

The native output format of the Calcpad output is Html. That is why everything works there at first.
Then the Html is converted to Word, but not all CSS and Html features are supported, only the most important ones.
So, if something does not work, it is simply because it is not supported. It is not possible at this moment to support for all CSS and Html features. They are too many, so it would be a project larger than the entire Calcpad.

For pdf we use [wkhtmtopdf](https://wkhtmltopdf.org/) that support more features. Unfortunately, for MS Word there is no such FOSS library that works for us, because they cannot create native Word equations and this is more important than some extra formatting.

**Comment by ThomsonTanminxin** [comment]
Thank you so much. I will prefer save as pdf. it's ok
.

**Comment by Proektsoftbg** [comment]
Yes, PDF is best if you do not need to change anything afterwards.

On the other side Word allows you to modify text and formulas but does not support all the formatting. Anyway, this is not such a big trouble, since you can use Word for formatting as well. It is even better than Calcpad for that purpose.
