### ISSUE TITLE
Doesn't ask to save modified file when opening another file

### ISSUE THREAD

**Issue by yuncu** [Proektsoftbg/Calcpad#21]
Hi,

Thanks for this incredible software.

When the file is modified and I try to exit, it asks for saving the file. But if I open an existing file instead, my changes are not saved and the second file is opened.

Best,

**Comment by Proektsoftbg** [comment]
Hi, 

Thank you for your feedback! I will try that on my side and will adjust the software accordingly.

**Comment by Proektsoftbg** [comment]
Hi, this was fixed in version 5.7:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.7.0

**Comment by yuncu** [comment]
Thanks, I confirm the issue is fixed.

**Comment by Proektsoftbg** [comment]
I found some minor bugs and fixed them today: 
1. The document sometimes is unnecessary marked as changed/unsaved, and prompts for save even though nothing has changed.
2. The "Save As..." dialog appears on "Save" even when the file has a name already. This can be very confusing when you click "Open", then click "yes", when prompted to save and see... the "Save As..." dialog, instead of "Open" dialog. I was just about to accidently replace a file.

However, I amended the current release, so you can download it again and try it.
