### ISSUE TITLE
Is it possiblen to support short calculation in input form

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#220]
α = ?{pi/6}rad

**Comment by idealkindom** [comment]
α = ?{pi/7}rad

**Comment by Proektsoftbg** [comment]
Hi! Currently not. Only numerical values are allowed. But you can have input fields in short calculations, like:
`α = pi/? {7}*rad`
or you can make it like this:
n = ? {7}
`α = pi/n*rad`

There are two reasons not to allow code in input fields:
1. It is much more complicated and rarely needed. The code inside must be parsed, but a little bit differently.  We will have to change much of the way the program currently works.
2. Since Calcpad is also a web software like in [calcpad.eu](https://calcpad.eu/Worksheet/5/rectangular-slab), this can create a security hole, allowing users to place some potentially harmful code inside. So, this input must be also sanitized. This is not very easy, because the available sanitizers can also strip out some Calcpad code.

If other users also consider this necessary, we can plan such feature for the future, but it will not be easy and certainly not fast.
