### ISSUE TITLE
Unit error in rev/min conversion to radians per second

### ISSUE THREAD

**Issue by Itenium** [Proektsoftbg/Calcpad#229]
Good day. 

When I convert rpm to rad/s I use the following equation. 

N = 15 rpm
r = 0.5 m
ω = 2*π*N/rpm/60*rad/s
V = ω * r

The unit of  ω is then in rad/s.  However if one calculates V the unit is m/s°

The same happens if I use rev/min.

For example
N_rev_min = 60rev/min
r = 1m
ω_rev_min = N_rev_min|rad/s
V_rev_min = ω_rev_min*r

I think there is a error in the unit conversions, as the velocity should not have a degree symbol in it.

Please see attached program.
[RPM to rad_s.txt](https://github.com/Proektsoftbg/Calcpad/files/13249430/RPM.to.rad_s.txt)

**Comment by Proektsoftbg** [comment]
Hi! 

The problem comes at first that the angle units persist after calculations. But this allows you to make proper arithmetics and conversions with angles. So the actual units in which you get the answer is `6.28 m·rad/s`. I only cannot figure out why it replaces `rad` with `°`. I will check this. But you can force it by adding `|m*rad/s` at the end:
`V_rpm = ω_rpm*r|m*rad/s`

The solution is to divide by `1rad`, when you multiply by `r`. So, the correct code will look like:

```
'Inputs
N_rpm = 60rpm
N_rev_min = 60rev/min
r = 1m

'Calculations
ω_rpm = 2*π*rad*N_rpm|rad/s
V_rpm = ω_rpm/rad*r

ω_rev_min = N_rev_min|rad/s
V_rev_min = ω_rev_min/rad*r
```
Until I find how `rad` gets rewritten with `°` please use the vertical bar `|` to force radians in the output.
