### ISSUE TITLE
"Smart" brackets deactivation 

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#233]
In some cases I need to deactivate smart brackets because I wish to show the formulae "as is" on the textbook. 
Is it possible?

**Comment by BasilioPV** [comment]
i want to deactivate for a specific part:
#smartOFF
#smartON

**Comment by Proektsoftbg** [comment]
Hi! 

I am sorry, but this is not possible in Calcpad. After parsing, the equation is stored as [RPN](https://en.wikipedia.org/wiki/Reverse_Polish_notation). All brackets disappear then, because RPN does not use brackets.

Then the equation is rendered back in the desired format using the [Shunting yard](https://en.wikipedia.org/wiki/Shunting_yard_algorithm) algorithm. Then, brackets are restored but only where required by the order of operations.

If this is at only a few places, probably it will be easier to edit the equation after export to Word.

**Comment by BasilioPV** [comment]
Ok, thanks
