### ISSUE TITLE
CLI Enhacements

### ISSUE THREAD

**Issue by berkdemir** [Proektsoftbg/Calcpad#245]
Hi,
I use CLI a lot, as a calculator. Actually, instead of using calculator, I would like to use CLI always. My problem is, there is no easy access to CLI.
(1) I cannot pin it to the taskbar, because when I pin it, it is a terminal, not CLI.
![image](https://github.com/Proektsoftbg/Calcpad/assets/40423004/ae4a38eb-3f35-4473-a6cc-59aabaa0c2ea)
(2) The best thing would be having a Windows wide shortcut. That would be amazing.

I know CLI is not a priority, but opening a Calcpad for quick calculations is an overkill.

**Comment by Proektsoftbg** [comment]
Hi, Demir!

I am glad that at least one person is using it. :)
Probably, you pin the running application on the taskbar itself. That is why it pins the terminal instead.

You have an icon on the desktop named 'Cli'. Right click on the icon, click 'Show more options' if on Windows 10/11 and then 'Pin to taskbar'. This will pin the actual Cli module rather than Terminal.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/fba681f8-ff10-401d-959f-e3f4c2d4d3ac) 
![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/ab2d139b-fd48-44b5-8f97-a8a565942482)

**Comment by berkdemir** [comment]
Perfect, thanks! It opens as a seperate window from the shortcut, but it works.
Maybe you can think about having a icon for next release, a small CLI written on the existing icon? Admin users can change it of course by themselves.
