### ISSUE TITLE
 recognition of the native c# function

### ISSUE THREAD

**Issue by michaldengusiak** [Proektsoftbg/Calcpad#253]
Is there a way to get recognition of the native c# function?

![image](https://github.com/Proektsoftbg/Calcpad/assets/26113670/0458d559-9216-41cb-862d-5d55b352dcba)

**Comment by Proektsoftbg** [comment]
Hi! 

No, you cannot do this in Calcpad. But you can use the Calcpad functions Exp() and e^x instead.
Otherwise there will be difficulties with formatting such code in the report. And since Calcpad is designed as a web based platform, this will also create security risks.

If you need C#, you can do the opposite - use Calcpad from inside C# as a library.
The "Cli" project is a worked example now to do that. It takes the expression, gives it to the Calcpad.Code to parse and calculate and displays the results:

https://github.com/Proektsoftbg/Calcpad/blob/main/Calcpad.Cli/Program.cs
