### ISSUE TITLE
Text Formatting Options

### ISSUE THREAD

**Issue by murilo-s** [Proektsoftbg/Calcpad#263]
Hi,

I would like to suggest creating some additional text formatting options with different colors (blue and green). A good option, would be to give the user an option to create specific formatting to be used with shortcuts or through the "Insert-Html" options.

![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/5b5665cb-4d33-41da-8bb3-1fc4fb3a45e9)

**Comment by Proektsoftbg** [comment]
Hi!

Thank you for your feedback! Since there are many colors, probably the best will be to have some color picker that can insert any color. With time, we will improve these things. Alternatively, you can just write it as Html:
'<font color="blue">Blue</font>

There are also two predefined classes that are intended mainly for design checks:
'<p class="ok">OK (Green)</p>
'<p class="err">ERR (Red)</p>

It is also possible to use some WYSIWYG Html editor to format the text and then, copy the Html source into Calcpad.
https://onlinehtmleditor.dev/

**Comment by murilo-s** [comment]
Thanks for your response. The color picker is a great idea!

 I knew about the "err" class, but not the "ok" class. The problem with the "err" class when using in the code is that it is easily confused with the system error output. See image below:
![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/4dbc3bd1-2796-4506-9587-a5c4f495dbb5)

I would suggest having a separated class for system error warning, so it is not to be confused with a design check.

**Comment by Proektsoftbg** [comment]
I do not think this is such a big trouble. The purpose of colors is to draw your attention. Then you will read the text and certainly will have to correct the compiler errors. So, the final user of the worksheet should see only the design ones.

If you want a different style, you can define it at the beginning of the worksheet, with just one line:
`'<style>.fail {color:red;}</style>`

I would like to avoid making Calcpad too complicated at this time with so many predefined styles and small features, but keep it as simple as possible. I think that it is actually an advantage.
