### ISSUE TITLE
Calculation with units (V6.2.2) 

### ISSUE THREAD

**Issue by ThomsonTanminxin** [Proektsoftbg/Calcpad#294]
It seems that all the calculations don't work properly in this version. The error is "Unexpected error: Object reference not set to an instance of an object. Please check the expression consistency."
<img width="832" alt="uniterror" src="https://github.com/Proektsoftbg/Calcpad/assets/14814935/edad2294-5d58-43a1-af69-913e6c0d7940">

**Comment by marcostrmuniz** [comment]
It's working fine for me 
![image](https://github.com/Proektsoftbg/Calcpad/assets/47599401/a7d30cd2-1c33-463a-9979-36ad25e5359d)

**Comment by Proektsoftbg** [comment]
OK. I see. Sorry, my fault. Sometimes when you fix one thing, you mess up another. ;) I will fix this right now.

**Comment by Proektsoftbg** [comment]
It is fixed now. You can download and reinstall it from the same link:
https://github.com/Proektsoftbg/Calcpad/releases/download/v6.2.2/calcpad-setup-en-x64.exe

Since it is the same release number, **uninstall** the old one first, and then **install** the new to make sure everything will be **replaced** properly,

Thank you for your feedback.

**Comment by ThomsonTanminxin** [comment]
> It is fixed now. You can download and reinstall it from the same link: https://github.com/Proektsoftbg/Calcpad/releases/download/v6.2.2/calcpad-setup-en-x64.exe
> 
> Since it is the same release number, **uninstall** the old one first, and then **install** the new to make sure everything will be **replaced** properly,
> 
> Thank you for your feedback.

It works now. Thank you Ned
