### ISSUE TITLE
some special character for variable definition

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#3]
this is related to concrete strength notation in ACI318 with typing as f'_c and contains a character.  unfortunately  Calcpad thrown an error messages. could it be accepted in the next or future versions?

![2022-02-16 18_04_41-2022-02-16 18_02_01-Untitled 1 - OpenOffice Writer](https://user-images.githubusercontent.com/72367311/154251944-cc5e1d62-d656-4522-b0fb-fcb1f051a09a.jpg)

![2022-02-16 18_04_01-2022-02-16 17_49_41-Calcpad 5 6 1](https://user-images.githubusercontent.com/72367311/154253157-746e519f-761f-48ee-aa92-06aad6becda5.jpg)

**Comment by Proektsoftbg** [comment]
Hi,

The problem is that the single quote character ' is reserved for other purposes. It is used to start a text/Html comment.This is what happens in your case. Also, the ^ symbol is the exponentiation operator. You can not use it to escape characters. The good news is that Unicode includes a special "[prime](https://www.compart.com/en/unicode/U+2032)" symbol ′ that is intended exactly for the purpose. Although it looks almost the same, it is a different character. So, I added this stymbol in Calcpad and made the parser to allow it for variable names:

![image](https://user-images.githubusercontent.com/90918363/154728260-7083f7e2-8e81-47cf-bbdb-dc316393cf45.png)

I did the same for doulbe ″, triple ‴, upto quadruple ⁗ prime. I also added the full set of Greek characters and a button to swich to uppercase. i made a small release 5.6.2 that includes the above changes. You can download it from the following link:

https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-setup-en-x64.exe

Just for case, uninstall the old version before installing the new one. If any other characters are needed, it is easy to include them quickly.

**Comment by xyont** [comment]
excited, it's special notation features has been implemented within a hours.  so many thanks, wish you gained support from many country and institutions in the next futures.

![2022-02-19 02_35_12-Calcpad 5 6 2 - learncp3 cpd](https://user-images.githubusercontent.com/72367311/154750963-39c64490-c11c-43a2-9f0e-cf101c9816bd.png)
