### ISSUE TITLE
Issue with div 

### ISSUE THREAD

**Issue by RenanMG84** [Proektsoftbg/Calcpad#331]
Hi @Proektsoftbg ! 

The "div " fold is not hiding totally the equations or texts as you can see in the figure below. It happens all the time.
I tried to do some html and css code to fix it but without sucess. Could you help me please?
![issue](https://github.com/Proektsoftbg/Calcpad/assets/152290118/42a4a724-53c0-4a26-acd6-f09c4bc979d2)

Thank you !

Ps: I dont know much about html code, I just copied the code from calcpad help:
  '<div class="fold">
  '<b>Heading</b> (click to unfold)
  'Content to be folded
  '</div>

**Comment by Proektsoftbg** [comment]
Hi! 

This is maybe because you do not have paragraphs around bold Html tags `<b> </b>` .
By default, Calcpad automatially puts each line of simple text or equation in a separate paragraph `<p> </p>`.

But it does not do that when you use your own Html, because it is possible to break it (e.g. in case of tables). So you have to put it by yourself: `<p><b> </b></p>`. If you do that, probably you will not have problem with the content flow.

**Comment by RenanMG84** [comment]
Thank you!! It worked ! 
But just to give feedback, there's still a little bit of code left showing up! ! See below.
![issue 2](https://github.com/Proektsoftbg/Calcpad/assets/152290118/db26a429-1509-4439-9beb-1281aa85a2d8)
