### ISSUE TITLE
Frame example - adding braces

### ISSUE THREAD

**Issue by FEA-eng** [Proektsoftbg/Calcpad#363]
Hi,

I'm exploring the amazing new capabilities of Calcpad (many thanks for them) and I got interested in the frame FEM example. I've noticed that it requires continuous definition of the members (subsequent nodes are always connected by members). This means that braced frames can't be defined. Would it be difficult to extend this example to cover such cases?

**Comment by Proektsoftbg** [comment]
Hi! Thank you but this is not the case. In vector e_J you specify element connecting joints. You have to enter two values - one for the number of the starting joint and one for the ending joint. There are no limitations except for that they should be between 1 and n_J, incl. For example, bracing joints for the same frame can be J1-J4 and J2-J5. So, the vector will look as follows:

`e_J = [1; 2|2; 3|3; 4|4; 5|1; 4|2; 5]`

![image](https://github.com/user-attachments/assets/5ddf8ac2-d25e-4367-b0cf-bdbddb97bb26)

Also, you have to assign some materials and sections to the new elements:

```
'Assignments on elements -'e_M = [1; 2; 2; 1; 1; 1]' (materials)
'Assignments on elements -'e_S = [1; 2; 2; 1; 1; 1]' (sections)
```

**Comment by FEA-eng** [comment]
Thank you, now it's clear. But point (nodal) loads are not supported, right? Only elemental (distributed) ones?

Also, can I define 1 support and 1 load? Deleting rows in c and q leads to errors:

![errors](https://github.com/user-attachments/assets/e39a7666-419c-4efb-9208-963c24a20174)

As a workaround, I can set 0 for unnecessary loads and supports though.

I'm trying to solve this kind of a frame:

![frame](https://github.com/user-attachments/assets/bc85ecbc-f292-485d-b6c3-df4d55267723)

P.S. Once I figure it out, I'll be glad to share a step-by-step tutorial for this frame analysis program for other users.

**Comment by Proektsoftbg** [comment]
Hi!

Since you have the source code, you can do absolutely anything without restrictions.
Joint loads are not included in this example, but you can add them by yourself. You can create a similar input matrix as for the element loads:

`P =[Joint; F_x\*kN; F_y\*kN; M\*kNm]`

Then, you can add them directly to the load vector by using the Joint indexes from the first column. See how element joint end forces are added after line 265.

About single support and load, the problem is that after you delete the remaining rows, you end up with a single vector, not a matrix. You can see the arrow. So later indexing fail because one index is now expected. One possible solution is to convert vectors back to matrices, by using, say **join_rows** function with a single argument.

`q = join_rows([1; 10kN/m; 0kN/m])`

BTW, great example for a tutorial. Thank you so much for your efforts. If any other questions, I would be glad to help.
