### ISSUE TITLE
The ( perhaps ) confusing display of results when calculating imaginary numbers.

### ISSUE THREAD

**Issue by Maaaaark001** [Proektsoftbg/Calcpad#382]
Hi! When power operations on purely imaginary numbers are performed, as shown below, the brackets are omitted from the rendered result, and the CODE section seems to treat 2i as a whole part, not 2*i.

![image](https://github.com/user-attachments/assets/31b69112-df9e-4c71-9937-a20642a320ad)

I think this is treating i as a unit rather than a sign. Yes, that is understandable, but as the displayed result shows, i is neither italicized nor represented by any other special color. When just viewing the output, it can be confusing: what exactly is being done to i?

Generally, in other calculators, the first line of CODE is kept in parentheses for display, and the second line of CODE is considered to be 2*(i)^2. I've listed below the display results for Mathematica, Nspire, Classpad, and GeoGebra calculators.In all of these calculators, the power operation is only for the immediate neighbor i, treating 2 and i as two parts rather than one whole. nspire even goes a step further, supplementing the * sign between 2 and i.
![Mathematica](https://github.com/user-attachments/assets/11190333-475e-486f-8987-cacfee96a0c0)
![Nspire](https://github.com/user-attachments/assets/e4e5a7ef-e5bd-47ee-b00b-10f6e9c0ba37)
![Classpad](https://github.com/user-attachments/assets/5ba11ff4-02d5-4559-b089-7056f1b1dd8f)
![GeoGebra](https://github.com/user-attachments/assets/24d6c1cb-0828-41fe-978c-4c268a68cd2d)

English is not my first language, and I apologize in advance for any expressions that may have been rude. This Issue is simply to discuss with you whether there is something misleading in displaying it in this way. Your software is very useful, and I often use it to record mathematical derivations in my studies. Thank you for your efforts!

**Comment by Proektsoftbg** [comment]
Hi! What happen in these programs if you write `2 x`?

**Comment by Proektsoftbg** [comment]
Hi, again! Now I have more time to provide more detailed explanations.

In facr, I  do not see any problem with imaginary numbers in Calcpad. Different porgrams just has different syntax and assumptions. In math, when you write `2i` without · or space this is a complete imaginary number, not "real 2 multiplied by the imaginary unit". The same is in Calcpad:

![image](https://github.com/user-attachments/assets/999a55e2-82c5-4cf2-8373-508aadb43eed)

It is not treated as a unit. It is an integral part of the number itself - a suffix indicating that the number is imaginary. So, "i" is formatted as a number, not unit or variable in this case. But in Calcpad you do both, because there is also a spacial prefedined variable _i_. If you write `2*i^2` then you will have what you want - real 2, muliplied by the imaginary unit squared, and exponentiation will be applied before multiplication. BTW Mathcad works exactly as Calcpad with the only difference that there is no internal variable _i_, and you have to define it explicitly.

<img width="93" alt="{E1CEFA5A-CB2E-4196-9421-46ABB5A84CE5}" src="https://github.com/user-attachments/assets/92866e05-1b06-40de-8389-7b50f61dc3ab">

I think that the confusion comes from the other softwares that allow you to write implicit multiplication `2 x`, instead of explicit `2*x` as we do on paper. This is exactly equivalent to the second option in Calcpad but the muliplication is actually there. We are not forced by any rule to always break imaginary numbers `bi` to `b*i.` And if we do it in Calcpad, it would be wrong. Now the Calcpad is quite clear and consistent for that.

**Comment by Maaaaark001** [comment]
> Hi, again! Now I have more time to provide more detailed explanations.
> 
> In facr, I do not see any problem with imaginary numbers in Calcpad. Different porgrams just has different syntax and assumptions. In math, when you write `2i` without · or space this is a complete imaginary number, not "real 2 multiplied by the imaginary unit". The same is in Calcpad:
> 
> ![image](https://private-user-images.githubusercontent.com/90918363/384078138-999a55e2-82c5-4cf2-8373-508aadb43eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzI0NTcsIm5iZiI6MTczMTAzMjE1NywicGF0aCI6Ii85MDkxODM2My8zODQwNzgxMzgtOTk5YTU1ZTItODJjNS00Y2YyLTgzNzMtNTA4YWFkYjQzZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAyMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMmY2NDI3YjYxZWI5ZWMyNTI1MTY0ZTM0NGE5MDZkMjAzNjAyOTYzNmZmZjJlZmQwYTA1NmRkMzlhYWZjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TbMTSzNEgWVXYsKgupAuKV5ZhHtULNExiI8ZnbI6BUQ)
> 
> It is not treated as a unit. It is an integral part of the number itself - a suffix indicating that the number is imaginary. So, "i" is formatted as a number, not unit or variable in this case. But in Calcpad you do both, because there is also a spacial prefedined variable _i_. If you write `2*i^2` then you will have what you want - real 2, muliplied by the imaginary unit squared, and exponentiation will be applied before multiplication. BTW Mathcad works exactly as Calcpad with the only difference that there is no internal variable _i_, and you have to define it explicitly.
> 
> <img alt="{E1CEFA5A-CB2E-4196-9421-46ABB5A84CE5}" width="93" src="https://private-user-images.githubusercontent.com/90918363/384077234-92866e05-1b06-40de-8389-7b50f61dc3ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzI0NTcsIm5iZiI6MTczMTAzMjE1NywicGF0aCI6Ii85MDkxODM2My8zODQwNzcyMzQtOTI4NjZlMDUtMWIwNi00MGRlLTgzODktN2I1MGY2MWRjM2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAyMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMWQ4NjhlNTg0N2VhMzcxNTllYjQ4NDJjNzk2OWRkYmM3ZGVmN2M2ZjQ1ZmI0OTlmMGY5OTc2MTk0ODk2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y4pGOuq-tmHKVq05A9WBoev_ytOJSIgGLdRrfs8fRsY">
> I think that the confusion comes from the other softwares that allow you to write implicit multiplication `2 x`, instead of explicit `2*x` as we do on paper. This is exactly equivalent to the second option in Calcpad but the multiplication is actually there. We are not forced by any rule to always break imaginary numbers `bi` to `b*i.` And if we do it in Calcpad, it would be wrong. Now Calcpad is quite clear and consistent for that.

Thank you for taking the time to explain this to me! I realized that Calcpad does not allow implicit multiplication. Yes, the software display does not cause any confusion with such a constraint. I completely agree with you.
Thanks again for your work!

**Comment by Proektsoftbg** [comment]
No problem. Thank you! :)
