### ISSUE TITLE
Conflict Between String Variable and Macro Parameter

### ISSUE THREAD

**Issue by strsthapa** [Proektsoftbg/Calcpad#386]
![string and macro variable name](https://github.com/user-attachments/assets/787d6a62-f76a-4fcf-be68-6714a1d1da7b)

1. when the string variable from last letter is similar to macro parameter it considers macro parameter instead of string variable.
2. can we provide code/math within while calling function? while calling function it is only passing the last value (in this case 3 instead of 6)
3. Can we assign output results from macro results to variable? Generally, calcpad assigns first value within macro line and shows error for non-number value.

**Comment by Proektsoftbg** [comment]
Hi$

Unlike normal variables, macro variables and parameters are allowed to be concatenated to other text without spaces. So, it is not always obvious where the variable starts from. For the end, there is no problem because all are required to end with $. So if you have two macro variables/parameters that are ends in the same way, e.g.: c$ and bc$, it is not disambiguous what `abc$` is: `ab` + `c$` or `a` + `bc$`. 

What Calcoad actually does in these cases: it parser the variable from right ($) to left and returns the first variable it finds (the fhortest one). So, just avoid variables that match letters at the end. Please use different names. There was a solution to this problem - to introcude a leading special symbol, like `_b$`, but it would require a lot of additional typing.
