### ISSUE TITLE
Strange Problem of solver

### ISSUE THREAD

**Issue by luckbiao** [Proektsoftbg/Calcpad#395]
![image](https://github.com/user-attachments/assets/7a2a7f77-03b9-4893-9171-d5bc79c75baf)

quadratic equation with one unknown

for Ag=2400 it works, but for Ag=2401 it failed

**Comment by Proektsoftbg** [comment]
Hi!

Thank you for your question. This is a very important topic. It is a question of selecting a good target precision.
By default Calcpad uses `Precision = 10^-15` which is very low. If you set `Precision = 10^-12` before the `$Root` function, it will work. Why is that?

Since your equation actually involves a constant term `R_g*A_g*e`, it would be more properly to express it in the form:

`$Root{f(x) = y @ x = 0 : h}`, 

where `y = R_g*A_g*e` and `f(x)` contains the rest. This now can be solved for `Precision = 10^-15`.

If you solve for `f(x) - y = 0` and `y` is of about 10^3 magintute, so will be 'f(x)' when approaching `y`. Subtarcting both will lead to cancelation of 3 significant digits due to the way floating point numbers are stored into the memory. They can hold not more than 17 significant digits (average 16). So you cannot achieve precision better than 10^-13. 

So, if you need to solve an equation in the form `f(x) - y = 0` you have to set the precision to be `Precision = 10^-15*y`.
In your case, just write `Precision = 10^-15*R_g*A_g*e` before calling the `$Root` function and it is always work.

**Comment by luckbiao** [comment]
"Thank you very much for your detailed explanation."




---Original---
From: "Ned ***@***.***&gt;
Date: Tue, Nov 26, 2024 17:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Proektsoftbg/Calcpad] Strange Problem of solver (Issue #395)




 
Hi!
 
Thank you for your question. This is a very important topic. It is a question of selecting a good target precision.
 By default Calcpad uses Precision = 10^-15 which is very low. If you set Precision = 10^-12 before the $Root function, it will work. Why is that?
 
Since your equation actually involves a constant term R_g*A_g*e, it would be more properly to express it in the form:
 
$Root{f(x) = y @ x = 0 : h},
 
where y = R_g*A_g*e and f(x) contains the rest. This now can be solved for Precision = 10^-15.
 
If you solve for f(x) - y = 0 and y is of about 10^3 magintute, so will be 'f(x)' when approaching y. Subtarcting both will lead to cancelation of 3 significant digits due to the way floating point numbers are stored into the memory. They can hold not more than 17 significant digits (average 16). So you cannot achieve precision better than 10^-13.
 
So, if you need to solve an equation in the form f(x) - y = 0 you have to set the precision to be Precision = 10^-15*y.
 In your case, just write Precision = 10^-15*R_g*A_g*e before calling the $Root function and it is always work.

**Comment by Proektsoftbg** [comment]
No, problem. Thank you for asking.

If you want to solve the quadratic equation analytically, please use the recommended equation in "What every scientist..." [1] and "Numerical  recipes in C", page 227 [2]:
![{AD7BD897-5E28-487F-83F1-53F1E5DED207}](https://github.com/user-attachments/assets/bc3150ae-9741-43aa-aba4-5c71ae1827e6)
Unlike the "classical" one it is not sensitive for floating point rounding errors.
References:
[1] https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
[2] https://nr304ob.s3.amazonaws.com/4G8102XTQPCMJ2XE.pdf
