### ISSUE TITLE
shortcut to typing Greek characters

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#4]
i did not found an options to submit a proposed enhancement or discussion, so this may be deleted if inappropriate.

regarding to typing engineering and mathematic equation, the document may contains lot of Greek characters. using a shortcut could be useful features since typing is accelerated and faster. user did not required to switch between keyboard and mouse mode.

below are common in similar applications, with shortcut as pressing Ctrl+G  and the same keystrokes for uppercase

'α' (Alpha) press 'a' and then shortcut.
'β' (Beta) press 'b' and then shortcut.
'γ' (Gamma) press 'g' and then shortcut.
'δ' (Delta) press 'd' and then shortcut.
'ε' (Epsilon) press 'e' and then shortcut.
'ζ' (Zeta) press 'z' and then shortcut.
'η' (Eta) press 'h' and then shortcut.
'θ' (Theta) press 'q' and then shortcut.
'ι' (Iota) press 'i' and then shortcut.
'κ' (Kappa) press 'k' and then shortcut.
'λ' (Lambda) press 'l' and then shortcut.
'μ' (Mu) press 'm' and then shortcut.
'ν' (Nu) press 'n' and then shortcut.
'ξ' (Xi) press 'x' and then shortcut.
'ο' (Omicron) press 'o' and then shortcut.
'π' (Pi) press 'p' and then shortcut.
'ρ' (Rho) press 'r' and then shortcut.
'σ' (Sigma) press 's' and then shortcut.
'τ' (Tau) press 't' and then shortcut.
'υ' (Upsilon) press 'u' and then shortcut.
'φ' (Phi) press 'f' and then shortcut.
'χ' (Chi) press 'c' and then shortcut.
'ψ' (Psi) press 'y' and then shortcut.
'ω' (Omega) press 'w' and then shortcut.

**Comment by Proektsoftbg** [comment]
Hi,

Thank you for the proposal. I find it very helpful. This is the way MathCAD wokrs and I like this feature very much.  So I added this option in the same way, you suggested. Since some Latin letters remained unused, I mapped them to some special symbols: j -> ø, J -> Ø, v -> ϑ, V -> ∡.

Because this is a minor change, I simply ammended the previous release. You can download the setup files from the same link:
https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-setup-en-x64.exe

First, uninstall the old version and install the new one after that.

**Comment by xyont** [comment]
so much thanks for appreciating, did not know that being developed. best wishes.
