### ISSUE TITLE
Disabled Word export tool after implementing Input Form?

### ISSUE THREAD

**Issue by j-desperado** [Proektsoftbg/Calcpad#423]
I need to export the cal pad output to word so I can get MathTtpe equations. The program was exporting the document to word but, at some point stop doing it. Now, when I export to Word, I just get a blank (empty) word file. Would be possible that implementing the Input forms created this issue? If so, how can I go back and remove the input form? Thank you

**Comment by Proektsoftbg** [comment]
Hi!

If you have broken Html inside, it may cause the problem. Maybe if you post your code, or part of it that do not export, we can provide more specific recomendations.

**Comment by j-desperado** [comment]
Got it, I'll debug it and look for the broken html. It's an extensive document so, I don't think it makes sense for me to upload. Btw, and FYI, I tried to copy and paste the code to another instance of calcpad (for creating a new version of the code for backup) and the new instance crashed. I think I need to do it piece by piece. Anyway, it's an outstanding software. I'm using it for my academic documents. It's like Jupyter Notes, but I like it more. Thank you for developing this for our community.

**Comment by j-desperado** [comment]
Hello-
One of the problems seems to be the hyperlink. I cleaned up the attached file.

[Example_debugging.txt](https://github.com/user-attachments/files/18141491/Example_debugging.txt)

**Comment by Proektsoftbg** [comment]
Hi!

Please, note that Calcpad puts automatically each line in a separate paragraph unless it find that the lines starts with an Html tag. Otherwise you will not be able to create other block level elements like tables, divs, etc. In order to be compatible with Word, inline elements like spans, links, u, i, b must be inside a block level one - e.g. paragraph or table cell.

So, you have to manually add paragraphs, when you start the line with an inline element. For example:
"<small>Example 1 - Two Span Bridge</small>` should become
`"<p><small>Example 1 - Two Span Bridge</small></p>`

and

`'<a href="https://www.google.com/">Google</a>` should become:
`'<p><a href="https://www.google.com/">Google</a></p>`

Also, you can start a paragraph on one line and close it on another line if all lines start with a tag:
```
'<h3>Example Seismic Design<hr/>
'<small>Example 1 - Two Span Bridge</small></h3>
```

**Comment by j-desperado** [comment]
Yes, that makes sense. I need to add the p-element before each in-line element. Thank you,
