### ISSUE TITLE
rad unitless unit

### ISSUE THREAD

**Issue by j-desperado** [Proektsoftbg/Calcpad#430]
Hello:

This is a conversation that started as a discussion but, I'd think it may need to be upgraded. 
I'm having problems in my documents where the rad unit never goes away.   I'm suggesting the default result for CalcPad for: 1rad is 1.
Here's an example from MathCad:
![image](https://github.com/user-attachments/assets/001327c1-9db5-4b61-88a1-1a1cbc0725d0)

This is what we currently have, which it may need to be revised:
![image](https://github.com/user-attachments/assets/fa1c684e-fce9-478d-9e4d-16da71e3a484)

If the user in CalcPad wants to enforce the rad, they could write: 1|rad.
would be possible to implement this feature in CalcPad wo/o affecting others?

Thank you,
J-Desperado

**Comment by Proektsoftbg** [comment]
Hi!

I know how Mathcad works, but Calcpad works differently, so we need to think carefully.

While in Mathcad you edit the formula in place, Calcpad can do variable substitution before showing the result. So, in order to properly convert and display different angle units, we need to keep them in a separate (non-physical) dimension layer. In Mathcad angle units are just constants (rad = 1, deg = pi/180, etc). They fall off immediately after calculation and not stored in the variable. In Calcpad we cannot just do that. Otherwise, you will not be able to have:

<img width="138" alt="{B1A64F18-C151-4A9C-AA13-F1DF9A717C32}" src="https://github.com/user-attachments/assets/3e852bbf-b409-4d40-a727-a2e5bba21a67" />

...which is the normal way in which Calcpad handle all units.

Also, in Mathcad default units for trigonometric functions are always radians. In Calcpad, you can set them globally to rad, deg or grad as calculators do or locally for a worksheet (`#deg`, `#rad`, `#grad`). So, if you have default units to deg, then `α = 1rad` and `β = 1` are not simply equal. Please, try this code:
```
α = 1rad
β = 1' (° - degrees)
sin(α)
sin(β)
```
![image](https://github.com/user-attachments/assets/b254d7f4-3640-4446-8114-0d9bcfb7d202)

There are also other cases, where rad is not equal to 1. In structural dynamics we have two frequencies: ω - angular frequencly (rad/s) and f - cyclic frequency (1/s or Hz). The are not equivalent: f = ω/2π rad. 

<img width="199" alt="{31C9431C-C6FA-4EA2-9625-D7FC992303B3}" src="https://github.com/user-attachments/assets/bc3c7c74-5389-431c-9c52-41330e3d601f" />

In Calcpad, trully dimernsionless units are %, ‰ and parts (pcm, ppm, etc). However, they should not implicitly mix and convert to angle units in order to allow using both in the same equation together.

Currently, unit handling in Calcpad is logical and consistent. We cannot just take an option from a program that work differently and patch another program with it. We will create a mess in this way. So, if you are converting angles to rotations as in the discussion, you are probably missing 'hidden' angle units. Write them expicitly or if you do not want to show this, hide the division in an Html comment:
`'<!--'α = α/rad'-->`

**Comment by j-desperado** [comment]
Hello Ned-

Thank you for your extensive, and detailed response. I think CalcPad is much superior than MathCad, and my intention was not patching CalcPad but rather, provide some examples.

Your above examples above are very valid, but my problem is related to the engineering approximation of small angles (i.e. sin(theta) ~ theta, cos(theta) ~ 0, etc).

I'm trying to do a plastic analysis where the lateral deflection of a cantilever column is equal to the rotation times the distance (assuming the angle is small).  How can I get rid of the radian in the example show below?

![image](https://github.com/user-attachments/assets/93a9426b-3066-465f-86d5-c65df10af07d)

**Comment by Proektsoftbg** [comment]
Hi! Thank you! I know that rad is dimensionless, and I can see and understand completely your point. You are right in theory, but here we speak about programming language convensions rather than physics. I alreay explained why Calcpad is made to work in this way. And still, rad remains dimensionless in a physical sence, but also Calcpad does not allow it to degrade to a unitless number for the reasons specified above.

However, your problem has a very simple solution in Calcpad. Just define the cuvature in ft<sup>-1</sup>:
`φ = 0.005ft^-1`
Since rad = 1, then rad/ft =  ft<sup>-1</sup>. In my own woskheets I always define curvarures in m<sup>-1</sup>.
However, if you need to display radians in the output, you can add them as text:
`φ = 0.005ft^-1'·rad`

Here are three solutions of your problem that you can choose from:
```
h_col = 25ft
'Solution with radians as text
#def rad$ = <span class="eq">· <i>rad</i></span>
φ = 0.005ft^-1'rad$
θ = φ*2ft'rad$
δ = θ*h_col
'Solution with hidden division
φ = 0.005rad/ft
θ = φ*2ft
'<!--'θ = θ/rad'-->'δ = θ*h_col
'Solution with custom radians proportional to parts
'<!--'.radians = 100%'-->'
φ = 0.005radians/ft
θ = φ*2ft
δ = θ*h_col
```

![image](https://github.com/user-attachments/assets/4be249a8-a592-4178-ac11-0d78fb00125e)

Nothing is perfect, but also not too bad. However, I wouldn't even bother about displaying radians in curvatures. Moreover, they are often expressed through the radius of curvature `r`, which is in `ft`. `φ = 1/r = 1/ft`.

**Comment by j-desperado** [comment]
This is great, I like the last solution which is creating my own unit. 
Yes, I understand the reasons for not implementing this, which is to keep consistency within the programs.  One of the things I don't like about MathCad is the band aids they seem to have implemented to solve shortcomings in their architecture.
