### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#49]
I noticed that all those give small values when they should return 0.
It is not a big deal since the values are very close to zero anyway.

![image](https://user-images.githubusercontent.com/111089248/186270496-e1b364f7-67b7-40b3-83d6-da7c1f1732f3.png)

**Comment by Proektsoftbg** [comment]
I am so glad that you opened this issue. Yes, this is completely true, but it is not a Calcpad issue. This is the way computer processors do floating point calculations in general. You can check this pure C# code in .NET fiddle:

https://dotnetfiddle.net/0UHyV1

You can see that it gives the same results. Floating point data types use limited set of bits to store real numbers, so calculations are subjected to rounding errors. They are ussually small and neglectable, except for some special cases of ill-conditioned problems/algorithms. We even do not use the actual pi, but some approximation of it. You can find more detailed information about that here:

https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

https://www.itu.dk/%7Esestoft/bachelor/IEEE754_article.pdf

http://numerical.recipes/

About trigonometric functions, they are transcedential and can be calculated by infinite series to certain precision. However, contemporary processors use a more effective BKM or CORDIC device for that purpose:

https://www.jacques-laporte.org/Volder_CORDIC.pdf

For greater values, the argument is shifted by times*pi. That is why, you get greater error in the last row of the .NET fiddle example above.

Some advanced CAS like Wolfram use symbolic arithmetic or arbitrary precission calculations to avoid or minimze rounding errors. But since this is software emulated, there is a big trade-off with performance. Although Calcpad uses floating point arithmetic, its algorithms are carefully designed in respect to stability and precision.

For example, numerical differentiation if performed by Richardson's extrapolation, which greatly improves the accuracy. You can check the Slope method in the solver source code:

https://github.com/Proektsoftbg/Calcpad/blob/main/Calcpad.Core/Solver.cs

Otherwise, it would be prone to catastrophic cancellation as discussed in the Wikipedia article above. I am currently writing some papers about the numerical methods in Calcpad. I will share them here when published.

**Comment by Proektsoftbg** [comment]
Additional to the above discussion, I created a chart of sin(pi*10^n) for n = 0 to 20, with LibreOffice Calc. 
![image](https://user-images.githubusercontent.com/90918363/186366359-025a9696-4ffa-4ac1-8a72-b0220818ec75.png)

You can see that for n > 16, we loose almost all significant digits and the result gets completely wrong. For that reason, we have limited the arguments of trig functions upto 10^10. That gives and error of about 10^-6, which is quite enough for structural engineering calculations.

What we can do about precision is to implement  IEEE 754 quadriple precision floating point format (_float128):

https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format

But until we get 128-bit computers, it will be software emulated and much slower. So, it could be an alternative option for those who need higher precision. However, for everday engieering problems, like those in the "Examples" folder, it will not make any noticeable difference.

**Comment by cser** [comment]
I also came across this bug (when generate svg).
But I haven't idea how to fix it on CalcPad level without new more harmful problems and bugs - so wasn't post it

**Comment by Proektsoftbg** [comment]
@cser it is not a bug, it is a feature. :) Use the round() function to round the numbers to the precision you need for SVG files:

`round_n(x; n) = round(x*10^n)/10^n`

![image](https://user-images.githubusercontent.com/90918363/186376499-c254485b-469a-4e0f-b568-e0257d858e6d.png)

**Comment by cser** [comment]
@Proektsoftbg: It's clear, I did just like that.

**Comment by jgagnonNT** [comment]
I did not expect such a complete answer! Very interesting and much appreciated!

**Comment by Proektsoftbg** [comment]
Thank you! 

It is good to know how computers work internally, if you are going to program engineering calculations. I've beed doing that for years, and I was happy to share what I've learned so far. :)

**Comment by Proektsoftbg** [comment]
I see that the next version of .NET 7.0 includes special trigonometric functions that have "times" `PI` argumens, e.g.:
`SinPi(x)`, `CosPi(x)`, `TanPi(x)`, etc. Instead of calling `sin(x * pi)`, you have to call `SinPi(x)`.

https://docs.microsoft.com/en-us/dotnet/api/system.double.sinpi?view=net-7.0

These functions produce much more accurate results for such arguments as if `PI` is precisely defined. They are available in Python and Julia for a long time and now I am glad that C# developers will also benefit from them.

It will be released on Nov 2022. We will then add these functions to Calcpad. We can even detect if the argument of a standard trigonometric function is an integer, fraction or rational number "times" `PI` and automatically switch to the "Pi" version. Then, this problem will be eventually solved.
