### ISSUE TITLE
#noc: Unexpected error for missing function

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#53]
Another unexpected error with #noc:
```nginx
#noc
x = 2*β(T)
```
Shows: Error in "x = [2](about:blank#0)*β(T)" on line [2]: Invalid function: "β"
It's strange to define functions for show it "as is"

**Comment by Proektsoftbg** [comment]
Hi, @cser!  This is not so easy to fix now. Unlike variables, functions and operators are resolved at parsing stage. The lexer checks if they exist or it is simply a syntax error.

Please, remember that Calcpad was not originally intended to be used as formula editor like LaTeX or MathType. It performs full syntax checking, so it is normal for it to check for undeclared functions and variables. 

For now, I only made a quick fix by removing calculations and display just formulas. It was also easy to remove variable checking and I did it. All other Calcpad errors are **expected**. Since, everything is now tightly integrated, it will require significant refactoring to separate parsing, needed for formatting only. Also, I think that it is good for a system like Calcpad to keep variable and function name checking. In many situation, it may help you to avoid typing errors.

If we need to make Calcpad to be used like pure math/equation editor, it would be better to clone it as a separate project/application.

For now, you will have to declare functions before using them in the text. This is very easy to do. Just make a hidden section in the beginning and initialize the function simply with: `β(T) = 0`.

**Comment by cser** [comment]
Thanks for answer, Ned!
Well, no - means no - I'll survive. I just had to try.
