### ISSUE TITLE
≡,≤,≥ unexpected replacing

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#54]
When I open this file
```
'==TITLE==
```
It converts to this:
```
'≡TITLE≡
```
It's expected that Calcpad will change == to ≡ on _input_, and don't touch already inputed text

**Comment by Proektsoftbg** [comment]
No, it is not intended to work line that. Otherwise, you will not be able to use these shortcuts (==, !=, ...) in external editors. You will always have to use ≡, ≠, etc. It would be very inconvenient, because you do not even have these buttons there. I think that this is more improtant. 

What we can do here is to replace only shortcuts that are outside comments and do not touch text in comments. I think that will do the job for you.

**Comment by Proektsoftbg** [comment]
OK, I fixed this in version 5.8.4:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.4

Text in comments is not replaced now.

**Comment by cser** [comment]
Thanks! Let it be so. Tested
