### ISSUE TITLE
Feature request: abs(x) showing like a |x|

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#75]
The expression abs(x) in the output is hard to read, sqrt(x) is now displayed as √x, maybe abs(x) need to show as |x| too?

**Comment by cser** [comment]
P.S. Within code it's impossible to replace `abs` by `||` - no way to separate opening `|` from closing `|`. Only the html displaying remains

**Comment by Proektsoftbg** [comment]
Yes, It is possible and also very easy to rewrite `abs(x)` with `| x |` in the output. I will inbclude it in the next update. Thank you for this suggestion.

**Comment by cser** [comment]
> Yes, It is possible and also very easy to rewrite `abs(x)` with `| x |` in the output
May be very easy, but there are nuances with bracket sizes
![image](https://user-images.githubusercontent.com/655339/193983366-d50dbe2c-5b0a-4bd4-8b6c-6499ba51a2ef.png)

**Comment by Proektsoftbg** [comment]
Yes, you are perfectly right. Thank you for pointing that out. But we already developed that for the normal brackets, so we will use the same for abs brackets. 

Additional imrovement can be made as well. Even if brackets are of the same size, outer ones can be just a little larger than innter ones as it is on Libre Office. Otherwise, as it is on the first equation in your example, it is a bit difficult to follow.

**Comment by Proektsoftbg** [comment]
Fixed in v5.8.8.

**Comment by cser** [comment]
Thank you!
But there remains one problem with superfluous normal brackets:
```
x = 10
abs(x + 1)'✔ shows |x+1|
abs(-x + 1)'✔ shows |-x+1|
1 + abs(x + 1)'✔ shows 1+|x+1|
1 + abs(-x + 1)'❌ shows |1+(|-x+1|)| - superfluous brackets
```

**Comment by Proektsoftbg** [comment]
Thank you for your feedback. Now it works. I amended the last release v5.8.8.

![image](https://user-images.githubusercontent.com/90918363/195018915-4c6de22c-e53f-46ff-a5ae-a1c0fa46578c.png)

**Comment by cser** [comment]
Yes! Now it fixed
