### ISSUE TITLE
force units conversions (kip)

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#9]
some behavior is not as expected for me, converting units of force from 'kN' to 'kip' thrown an error message and reported as incompatible.

![2022-02-25 00_16_05-Calcpad 5 6 2](https://user-images.githubusercontent.com/72367311/155574828-9e68e3ad-0cdd-4f02-9333-ca0bec9e0bb9.png)

**Comment by Proektsoftbg** [comment]
Hi,

This is because the program makes difference between pound as mass and pound as force (pound-force). The same is for other units like kilogram, tonne etc. So, if you have mass, use: oz, lb, kip, ton, kg, t. If you have force, just add "f" at the end: ozf, lbf, kipf, tonf, kgf, tf. You cannot use mass units for forces.

**Comment by xyont** [comment]
well, is a bit different with another were actually is wrong. i'm familiar with 'kg'  or 'ton' mass and 'kgf' or'tonf' forces but not for 'pound' units. thanks for the hints.

![2022-02-25 10_25_57-SMath Studio -  Worksheet1_](https://user-images.githubusercontent.com/72367311/155648285-baa970ab-b606-459a-b084-074ff83cd9bb.png)

**Comment by xyont** [comment]
but may it be skipped and closed due to clear representation of 'f' at the end of units

**Comment by Proektsoftbg** [comment]
The name of the unit is "**pound**", but the symbol, that we use is "**lb**". So **lb** = **pound**. Sometimes lbm is used instead, mostly in USA.
https://en.wikipedia.org/wiki/Pound_(mass)

For structural calcs in USA they often use **lb** and **kip** for forces because it is easier and faster to write. But, when you need to clearly distinguish force from mass, **lbf** and **kipf** are commonly accepted and recognized.
